### PR TITLE
Fixes #2984 by considering already existing framework:id node before …

### LINKED ISSUE #2984: Failed migration 0.11.1 -> 0.14.0-RC3
Turns out #2405 did not help. I tried upgrade from 0.11.1 -> 0.14.0-RC3 before, but it failed. New run fails too:

```
[2016-01-13 23:59:04,275] ERROR Failed to take over leadership (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$348337d4:pool-1-thread-2)
mesosphere.marathon.MigrationFailedException: while migrating storage to 0.13
	at mesosphere.marathon.state.Migration$$anonfun$migrations$4$$anonfun$apply$2.applyOrElse(Migration.scala:61) ~[marathon-assembly-0.14.0-RC3.jar:0.14.0-RC3]
	at mesosphere.marathon.state.Migration$$anonfun$migrations$4$$anonfun$apply$2.applyOrElse(Migration.scala:60) ~[marathon-assembly-0.14.0-RC3.jar:0.14.0-RC3]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[marathon-assembly-0.14.0-RC3.jar:0.14.0-RC3]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216) ~[marathon-assembly-0.14.0-RC3.jar:0.14.0-RC3]
	at scala.util.Try$.apply(Try.scala:192) ~[marathon-assembly-0.14.0-RC3.jar:0.14.0-RC3]
	at scala.util.Failure.recover(Try.scala:216) ~[marathon-assembly-0.14.0-RC3.jar:0.14.0-RC3]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) ~[marathon-assembly-0.14.0-RC3.jar:0.14.0-RC3]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) ~[marathon-assembly-0.14.0-RC3.jar:0.14.0-RC3]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) ~[marathon-assembly-0.14.0-RC3.jar:0.14.0-RC3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66-internal]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66-internal]
Caused by: mesosphere.marathon.StoreCommandFailedException: Can not create entity framework:id
	at mesosphere.util.state.zk.ZKStore$$anonfun$exceptionTransform$1.applyOrElse(ZKStore.scala:84) ~[marathon-assembly-0.14.0-RC3.jar:0.14.0-RC3]
	at mesosphere.util.state.zk.ZKStore$$anonfun$exceptionTransform$1.applyOrElse(ZKStore.scala:83) ~[marathon-assembly-0.14.0-RC3.jar:0.14.0-RC3]
	... 10 common frames omitted
Caused by: org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /marathons/scan/state/framework:id
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:119) ~[marathon-assembly-0.14.0-RC3.jar:0.14.0-RC3]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[marathon-assembly-0.14.0-RC3.jar:0.14.0-RC3]
	at com.twitter.zk.AsyncCallbackPromise$class.process(AsyncCallbackPromise.scala:18) ~[marathon-assembly-0.14.0-RC3.jar:0.14.0-RC3]
	at com.twitter.zk.StringCallbackPromise.process(AsyncCallbackPromise.scala:23) ~[marathon-assembly-0.14.0-RC3.jar:0.14.0-RC3]
	at com.twitter.zk.StringCallbackPromise.processResult(AsyncCallbackPromise.scala:25) ~[marathon-assembly-0.14.0-RC3.jar:0.14.0-RC3]
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:605) ~[marathon-assembly-0.14.0-RC3.jar:0.14.0-RC3]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498) ~[marathon-assembly-0.14.0-RC3.jar:0.14.0-RC3]
```

`frameworkId` znode exists, but not `framework:id`.

This only happened to one of 19 marathons we have and it can be easily fixed by redeploying, but still.

### PR DESCRIPTION
**Pull request by meichstedt**
…trying to migrate.

- frameworkId will only be migrated if framework:id not already exists.
- if a value is already stored in framework:id, this value wins
- added tests to verify correct behaviour

I made the frameworkId migration part a little more verbose so we can see in the logs what happened.

**Note:** This will need to be cherry picked into releasing-0.14

### CODE REVIEW

File: src/main/scala/mesosphere/marathon/state/Migration.scala [hunk 1]
```diff
@@ -364,9 +364,20 @@ class MigrationTo0_13(taskRepository: TaskRepository, store: PersistentStore) {
...
       } yield ()
     }
-    store.load(oldName).flatMap {
-      case Some(key) => moveKey(key.bytes)
-      case None      => Future.successful(())
+
+    store.load(newName).flatMap {
+      case Some(_) =>
+        log.info("framework:id already exists, no need to migrate")
+        Future.successful(())
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/state/Migration.scala]: you do not delete the "oldName" in this case, if it exists. But that shouldn't do any harm and actually I wouldn't know how to get into this situation, right?

**Comment by kolloch** [comment]
LGTM! Please confirm my comment, though.

Waiting for the tests.

File: src/main/scala/mesosphere/marathon/state/Migration.scala (hunk 1 above)
Comment (meichstedt) [inline src/main/scala/mesosphere/marathon/state/Migration.scala]: Exactly. I've thought about removing it, but its a corner case that's merely irritating if someone looks directly into zk.

If the `renameFrameworkId` crashes while deleting the old key (zk timeout or whatever), we _can_ end up here. Then the migration will be tried again, skips this step because the new key exists, and will finish successfully.
