### PR TITLE
Fixes #2178 MarathonTask.stagedAt pre-filled with current time

### LINKED ISSUE #2178: AppDeployIntegrationTest fails because tasks with stagedAt=0 are considered staging
`test("create and deploy an app with two tasks")` is failing with more or less unreadable log output. The two tasks are created but immediately killed by marathon:
```
marathon: [2015-09-03 09:32:39,818] WARN Task 'marathonintegrationtest_test_app.b8235d38-521e-11e5-ad1a-0242ac110004' was staged 1441272758s ago and has not yet started (mesosphere.marathon.tasks.TaskTracker$$EnhancerByGuice$$f6c75f17:166)
```
The problem is that the `TaskTracker`implementation does not consider the actual value of `stagedAt`, but assumes that a task is staged if `startedAt == 0`. However, stagedAt is currently set via the app version timestamp, which can be 0 in tests; and could even be very old in `real life`.

### PR DESCRIPTION
**Pull request by meichstedt**
Fixes #2178 MarathonTask.stagedAt needs to be pre-filled with a current timestamp (other than the version, which might be really old, not only in tests), because determineOverdueTasks in taskTracker will check against that timestamp whether a task exceeded the taskLaunchTimeout and needs to be killed.

### CODE REVIEW

File: src/main/scala/mesosphere/marathon/tasks/DefaultTaskFactory.scala [hunk 1]
```diff
@@ -26,8 +26,13 @@ class DefaultTaskFactory @Inject() (
...
           taskInfo,
           MarathonTasks.makeTask(
-            taskInfo.getTaskId.getValue, offer.getHostname, ports,
-            offer.getAttributesList.asScala, app.version, offer.getSlaveId
+            id = taskInfo.getTaskId.getValue,
+            host = offer.getHostname,
+            ports = ports,
+            attributes = offer.getAttributesList.asScala,
+            version = app.version,
+            now = Timestamp.now(),
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/tasks/DefaultTaskFactory.scala]: A clock would be better...

File: src/main/scala/mesosphere/marathon/core/task/tracker/impl/KillOverdueStagedTasksActor.scala [hunk 2]
```diff
@@ -30,9 +31,10 @@ private class KillOverdueStagedTasksActor(taskTracker: TaskTracker, driverHolder
 
   override def receive: Receive = {
     case KillOverdueStagedTasksActor.Check =>
+      val now = Timestamp.now()
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/core/task/tracker/impl/KillOverdueStagedTasksActor.scala]: Clock?

File: src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala [hunk 3]
```diff
@@ -474,4 +477,47 @@ class TaskTrackerTest extends MarathonSpec with Matchers {
 
     verify(state, times(1)).update(any())
   }
+
+  // sounds strange, but this is how it currently works: checkStagedTasks will only consider a missing startedAt to
+  // determine whether a task is in staging and might need to be killed if it exceeded the taskLaunchTimeout
+  test("ensure that checkStagedTasks returns tasks disregarding the stagedAt property") {
```
Comment (kolloch) [inline src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala]: Test name needs update

File: src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala [hunk 4]
```diff
@@ -474,4 +477,47 @@ class TaskTrackerTest extends MarathonSpec with Matchers {
...
+    val unstagedTask = MarathonTask.newBuilder()
+      .setId("unstaged")
+      .build()
+
+    val stagedTask = MarathonTask.newBuilder()
+      .setId("staged")
+      .setStagedAt(now - 10.seconds)
+      .build()
+
+    val withoutStagedAtTask = MarathonTask.newBuilder()
```
Comment (kolloch) [inline src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala]: Val name?

File: src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala [hunk 5]
```diff
@@ -474,4 +477,47 @@ class TaskTrackerTest extends MarathonSpec with Matchers {
...
+    // Given("several tasks of which not all have been staged yet")
+    taskTracker.created(TEST_APP_NAME, unstagedTask)
+    taskTracker.created(TEST_APP_NAME, withoutStagedAtTask)
+    taskTracker.created(TEST_APP_NAME, stagedTask)
+    taskTracker.created(TEST_APP_NAME, runningTask)
+
+    // When("staged tasks are queried")
+    val stagedTasks = taskTracker.checkStagedTasks(now)
+
+    // Then("Only the stagedTask ")
```
Comment (kolloch) [inline src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala]: Why is this commented out?

File: src/main/scala/mesosphere/marathon/tasks/DefaultTaskFactory.scala (hunk 1 above)
Comment (meichstedt) [inline src/main/scala/mesosphere/marathon/tasks/DefaultTaskFactory.scala]: Ok

File: src/main/scala/mesosphere/marathon/core/task/tracker/impl/KillOverdueStagedTasksActor.scala (hunk 2 above)
Comment (meichstedt) [inline src/main/scala/mesosphere/marathon/core/task/tracker/impl/KillOverdueStagedTasksActor.scala]: Aye

File: src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala (hunk 3 above)
Comment (meichstedt) [inline src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala]: Sure does, also changed the guts a little

File: src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala (hunk 4 above)
Comment (meichstedt) [inline src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala]: Yep

File: src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala (hunk 5 above)
Comment (meichstedt) [inline src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala]: I didn't want to mixin the GivenWhenThen trait into a test that otherwise doesn't make use of it, and I didn't want to also change the remaining. Mixed it in now, but only used it in the added test.

**Comment by meichstedt** [comment]
Integrated your comments, please review!

File: src/main/scala/mesosphere/marathon/core/task/tracker/TaskTrackerModule.scala [hunk 6]
```diff
@@ -15,7 +16,7 @@ import mesosphere.marathon.tasks.{ TaskIdUtil, TaskTracker }
 class TaskTrackerModule(leadershipModule: LeadershipModule) {
   def killOverdueTasks(taskTracker: TaskTracker, marathonSchedulerDriverHolder: MarathonSchedulerDriverHolder): Unit = {
     leadershipModule.startWhenLeader(
-      KillOverdueStagedTasksActor.props(taskTracker, marathonSchedulerDriverHolder),
+      KillOverdueStagedTasksActor.props(taskTracker, marathonSchedulerDriverHolder, Clock()),
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/core/task/tracker/TaskTrackerModule.scala]: You should use the global clock here.

File: src/main/scala/mesosphere/marathon/core/task/tracker/impl/KillOverdueStagedTasksActor.scala [hunk 7]
```diff
@@ -30,9 +33,10 @@ private class KillOverdueStagedTasksActor(taskTracker: TaskTracker, driverHolder
 
   override def receive: Receive = {
     case KillOverdueStagedTasksActor.Check =>
+      val now = clock.now()
       log.debug("checking for overdue tasks")
       driverHolder.driver.foreach { driver =>
-        taskTracker.checkStagedTasks.foreach { overdueTask =>
+        taskTracker.determineOverdueTasks(now).foreach { overdueTask =>
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/core/task/tracker/impl/KillOverdueStagedTasksActor.scala]: I like the name! Maybe rename the actor as well? (without staged)

File: src/main/scala/mesosphere/marathon/tasks/TaskTracker.scala [hunk 8]
```diff
@@ -269,13 +284,13 @@ class TaskTracker @Inject() (
     val key: String = getKey(appId, task.getId)
     timedWrite(fetchFromState(key) match {
       case Some(entity) => store.update(entity.withNewContent(bytes))
-      case None         => store.create(key, bytes)
+      case None => store.create(key, bytes)
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/tasks/TaskTracker.scala]: seems like you didn't reformat the code before submitting.

File: src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala [hunk 9]
```diff
@@ -474,4 +477,50 @@ class TaskTrackerTest extends MarathonSpec with Matchers {
 
     verify(state, times(1)).update(any())
   }
+
+  // sounds strange, but this is how it currently works: checkStagedTasks will consider a missing startedAt to
```
Comment (kolloch) [inline src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala]: determine... instead of checkStagedTasks

File: src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala [hunk 10]
```diff
@@ -474,4 +477,50 @@ class TaskTrackerTest extends MarathonSpec with Matchers {
...
+    taskTracker.created(TEST_APP_NAME, unstagedTask)
+    taskTracker.created(TEST_APP_NAME, stagedLongTimeAgoTask)
+    taskTracker.created(TEST_APP_NAME, stagedTask)
+    taskTracker.created(TEST_APP_NAME, runningTask)
+
+    When("We check which tasks should be killed because they're not yet staged")
+    val stagedTasks = taskTracker.determineOverdueTasks(now)
+
+    Then("Both the unstaged and the stagedLongAgo tasks are returned")
+    assert(unstagedTask.getStagedAt == 0, "The stagedAt property of an unstaged task has a value of 0")
```
Comment (kolloch) [inline src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala]: startedAt instead of getStagedAt. I would use that assert after constructing the unstagedTask, because it is more a requirement of the test data than an expected behavior of your tested code.

File: src/main/scala/mesosphere/marathon/tasks/MarathonTasks.scala [hunk 11]
```diff
@@ -8,11 +8,26 @@ import org.apache.mesos.Protos.Attribute
...
+   * This might either be introduced to prevent tasks from being killed right away, or to be able to enhance the
+   * semantic of staged at – stagedAt could be understood as some sort of createdAt, when there is no status set.
+   * Either
+   * way, please be aware of the fact that there is a stagedAt timestamp even though we've not heard anything from mesos
+   * yet.
+   *
+   * The general problem seems to be that we don't have a timestamp of when the task was created – if stagedAt would
+   * default to 0, we couldn't measure how 'old' the task is. So, _maybe_ the solution would be to just add a createdAt
+   * property and set that when the task is created.
+   */
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/tasks/MarathonTasks.scala]: I think that you can say that in fewer words. If you propose a different solution, I would rather create an issue for that.
 E.g.:

Despite its name, `stagedAt` is set on task creation and before the TASK_STAGED notification from Mesos. This is important because we periodically check for any tasks with an old `stagedAt` timestamp and kill them (See `KillOverdueStagedTasksActor`). If `stagedAt` remains 0 and this check is executed, the task will be killed immediately after being created.

File: src/main/scala/mesosphere/marathon/core/task/tracker/impl/KillOverdueStagedTasksActor.scala (hunk 7 above)
Comment (meichstedt) [inline src/main/scala/mesosphere/marathon/core/task/tracker/impl/KillOverdueStagedTasksActor.scala]: Done that

File: src/main/scala/mesosphere/marathon/tasks/TaskTracker.scala (hunk 8 above)
Comment (meichstedt) [inline src/main/scala/mesosphere/marathon/tasks/TaskTracker.scala]: Yup, fixed.

File: src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala (hunk 9 above)
Comment (meichstedt) [inline src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala]: fixed

File: src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala (hunk 10 above)
Comment (meichstedt) [inline src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala]: Agree, that's better. I now check getStartedAt and getStagedAt

File: src/main/scala/mesosphere/marathon/tasks/MarathonTasks.scala (hunk 11 above)
Comment (meichstedt) [inline src/main/scala/mesosphere/marathon/tasks/MarathonTasks.scala]: kk, will create a ticket and leave the text shorter

File: src/main/scala/mesosphere/marathon/core/task/tracker/TaskTrackerModule.scala (hunk 6 above)
Comment (meichstedt) [inline src/main/scala/mesosphere/marathon/core/task/tracker/TaskTrackerModule.scala]: done.

File: src/main/scala/mesosphere/marathon/tasks/TaskTracker.scala [hunk 12]
```diff
@@ -289,12 +304,13 @@ class TaskTracker @Inject() (
 object TaskTracker {
 
   private[marathon] class InternalApp(
-      val appName: PathId,
-      var tasks: TrieMap[String, MarathonTask],
-      var shutdown: Boolean) {
+                                       val appName: PathId,
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/tasks/TaskTracker.scala]: These instances of reformatting are somewhat strange. Did you do that on purpose?

File: src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala [hunk 13]
```diff
@@ -474,4 +477,51 @@ class TaskTrackerTest extends MarathonSpec with Matchers {
...
+      .setStagedAt(now - 10.days)
+      .build()
+
+    val runningTask = MarathonTask.newBuilder()
+      .setId("running")
+      .setStagedAt(now - 2.seconds)
+      .setStartedAt(now - 5.seconds)
+      .build()
+
+    Given("several tasks of which not all have been staged yet")
```
Comment (kolloch) [inline src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala]: that's wrong. There is one running task (and that's good to test!)

Comment (kolloch) [inline src/test/scala/mesosphere/marathon/tasks/TaskTrackerTest.scala]: and one staged task

**Comment by kolloch** [comment]
Great patch! Only two remaining cosmetic comments.

I wonder if you auto-formatting is set correctly.

**Comment by meichstedt** [comment]
ok, I integrated your comments!

**Comment by kolloch** [comment]
:ship: it!!
