### PR TITLE
Fixes #3579/#3477/#3597 - adjustments to restart logic

### LINKED ISSUE #3579: Resident Tasks: Flaky test: restart
```

[10:42:00][Step 3/3] - Restart *** FAILED *** (3 seconds, 130 milliseconds)
[10:42:00][Step 3/3]   false was not equal to true (ResidentTaskIntegrationTest.scala:159)
[10:42:00][Step 3/3]   org.scalatest.exceptions.TestFailedException:
[10:42:00][Step 3/3]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[10:42:00][Step 3/3]   at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6318)
[10:42:00][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$7.apply(ResidentTaskIntegrationTest.scala:159)
[10:42:00][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$7.apply(ResidentTaskIntegrationTest.scala:143)
[10:42:00][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$test$1.apply$mcV$sp(ResidentTaskIntegrationTest.scala:225)
[10:42:00][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$test$1.apply(ResidentTaskIntegrationTest.scala:225)
[10:42:00][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$test$1.apply(ResidentTaskIntegrationTest.scala:225)
[10:42:00][Step 3/3]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[10:42:00][Step 3/3]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[10:42:00][Step 3/3]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[10:42:00][Step 3/3]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[10:42:00][Step 3/3]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:158)
[10:42:00][Step 3/3]   at org.scalatest.Suite$class.withFixture(Suite.scala:1121)
[10:42:00][Step 3/3]   at org.scalatest.FunSuite.withFixture(FunSuite.scala:1559)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:155)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167)
[10:42:00][Step 3/3]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:167)
[10:42:00][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest.org$scalatest$BeforeAndAfter$$super$runTest(ResidentTaskIntegrationTest.scala:16)
[10:42:00][Step 3/3]   at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200)
[10:42:00][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest.runTest(ResidentTaskIntegrationTest.scala:16)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:200)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:200)
[10:42:00][Step 3/3]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[10:42:00][Step 3/3]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[10:42:00][Step 3/3]   at scala.collection.immutable.List.foreach(List.scala:381)
[10:42:00][Step 3/3]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[10:42:00][Step 3/3]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[10:42:00][Step 3/3]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:200)
[10:42:00][Step 3/3]   at org.scalatest.FunSuite.runTests(FunSuite.scala:1559)
[10:42:00][Step 3/3]   at org.scalatest.Suite$class.run(Suite.scala:1423)
[10:42:00][Step 3/3]   at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1559)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:204)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:204)
[10:42:00][Step 3/3]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:204)
[10:42:00][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest.org$scalatest$BeforeAndAfterAllConfigMap$$super$run(ResidentTaskIntegrationTest.scala:16)
[10:42:00][Step 3/3]   at org.scalatest.BeforeAndAfterAllConfigMap$class.liftedTree1$1(BeforeAndAfterAllConfigMap.scala:248)
[10:42:00][Step 3/3]   at org.scalatest.BeforeAndAfterAllConfigMap$class.run(BeforeAndAfterAllConfigMap.scala:247)
[10:42:00][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest.org$scalatest$BeforeAndAfter$$super$run(ResidentTaskIntegrationTest.scala:16)
[10:42:00][Step 3/3]   at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241)
```

(https://teamcity.mesosphere.io/viewLog.html?buildId=178347&buildTypeId=Oss_Marathon_IntegrationScaleTests&tab=buildLog#_focus=50222)

### PR DESCRIPTION
**Pull request by kolloch**

### CODE REVIEW

File: src/main/scala/mesosphere/marathon/upgrade/TaskReplaceActor.scala [hunk 1]
```diff
@@ -169,9 +163,43 @@ class TaskReplaceActor(
...
+  private[upgrade] def computeRestartStrategy(app: AppDefinition, runningTasksCount: Int): RestartStrategy = {
+    val minHealthy = (app.instances * app.upgradeStrategy.minimumHealthCapacity).ceil.toInt
+    var maxCapacity = (app.instances * (1 + app.upgradeStrategy.maximumOverCapacity)).toInt
+    var nrToKillImmediately = math.max(0, runningTasksCount - minHealthy)
+
+    if (minHealthy == maxCapacity) {
+      if (app.isResident) {
+        // Kill enough tasks so that we end up with end up with one task below minHealthy.
+        // TODO: We need to do this also while restarting, since the kill could get lost.
+        nrToKillImmediately = runningTasksCount - minHealthy + 1
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/upgrade/TaskReplaceActor.scala]: `runningTasksCount` could be below `minHealthy`
suggestion: max(runningTasksCount, minHealthy) - minHealthy + 1

File: src/main/scala/mesosphere/marathon/upgrade/TaskReplaceActor.scala [hunk 2]
```diff
@@ -169,9 +163,43 @@ class TaskReplaceActor(
...
+  /** Encapsulates the logic how to get a Restart going */
+  private[upgrade] case class RestartStrategy(nrToKillImmediately: Int, maxCapacity: Int)
+
+  private[upgrade] def computeRestartStrategy(app: AppDefinition, runningTasksCount: Int): RestartStrategy = {
+    val minHealthy = (app.instances * app.upgradeStrategy.minimumHealthCapacity).ceil.toInt
+    var maxCapacity = (app.instances * (1 + app.upgradeStrategy.maximumOverCapacity)).toInt
+    var nrToKillImmediately = math.max(0, runningTasksCount - minHealthy)
+
+    if (minHealthy == maxCapacity) {
+      if (app.isResident) {
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/upgrade/TaskReplaceActor.scala]: Just to make sure: according to our validation rules, this will never be true, right?

File: src/test/scala/mesosphere/marathon/upgrade/RestartStrategyTest.scala [hunk 3]
```diff
@@ -0,0 +1,132 @@
...
+
+    Then("the app instance count is not exceeded")
+    strategy.maxCapacity shouldBe 5
+
+    And("we kill one task")
+    strategy.nrToKillImmediately shouldBe 2
+  }
+
+  test("strategy for normal app with 1 instance") {
+    Given("A resident app")
```
Comment (aquamatthias) [inline src/test/scala/mesosphere/marathon/upgrade/RestartStrategyTest.scala]: which is not resident

File: src/test/scala/mesosphere/marathon/upgrade/RestartStrategyTest.scala [hunk 4]
```diff
@@ -0,0 +1,132 @@
...
+
+    Then("the app instance count is exceeded by one")
+    strategy.maxCapacity shouldBe 2
+
+    And("we kill 0 tasks immediately")
+    strategy.nrToKillImmediately shouldBe 0
+  }
+
+  test("maxCapacity strategy for normal app is not exceeded when a task can be killed immediately") {
+    Given("A resident app")
```
Comment (aquamatthias) [inline src/test/scala/mesosphere/marathon/upgrade/RestartStrategyTest.scala]: s/resident/normal

File: src/test/scala/mesosphere/marathon/upgrade/RestartStrategyTest.scala [hunk 5]
```diff
@@ -0,0 +1,132 @@
...
+      instances = 2,
+      upgradeStrategy = UpgradeStrategy(0.5, 0))
+
+    When("the ignition strategy is computed")
+    val strategy = computeRestartStrategy(app, app.instances)
+
+    Then("the app instance count is exceeded by one")
+    strategy.maxCapacity shouldBe 2
+
+    And("we kill 0 tasks immediately")
```
Comment (aquamatthias) [inline src/test/scala/mesosphere/marathon/upgrade/RestartStrategyTest.scala]: s/0/1

File: src/main/scala/mesosphere/marathon/upgrade/TaskReplaceActor.scala (hunk 2 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/upgrade/TaskReplaceActor.scala]: No, actually in our standard case that will be true.

minHealthy = (1 * 0.5).ceil.toInt = 1
maxCapacity = (1 * (1 + 0)).toInt = 1

**Comment by aquamatthias** [comment]
@kolloch the integration tests still fail for:
-ResidentTaskIntegrationTest: persistent volume will be re-attached and keep state 
-AppDeployIntegrationTest: backoff delays are reset on configuration changes
-AppDeployIntegrationTest: restarting an app with backoff delay starts immediately
Will rerun to see if this is related to this PR

**Comment by kolloch** [comment]
The tests seem to fail quite reproducible -- sorry for not checking after the last change. I will investigate.

File: src/main/scala/mesosphere/marathon/core/launcher/impl/OfferProcessorImpl.scala [hunk 6]
```diff
@@ -122,7 +122,7 @@ private[launcher] class OfferProcessorImpl(
   private[this] def saveTasks(ops: Seq[TaskOpWithSource], savingDeadline: Timestamp): Future[Seq[TaskOpWithSource]] = {
     def saveTask(taskOpWithSource: TaskOpWithSource): Future[Option[TaskOpWithSource]] = {
       val taskId = taskOpWithSource.taskId
-      log.info("Persisting TaskStateOp for [{}]", taskOpWithSource.taskId)
+      log.info("Processing {} for [{}]", Array[Object](taskOpWithSource.op.stateOp, taskOpWithSource.taskId): _*)
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/launcher/impl/OfferProcessorImpl.scala]: Nit: we are using log with format and `s""` randomly. Seeing this call I would opt for `s""`

File: src/main/scala/mesosphere/marathon/core/task/Task.scala [hunk 7]
```diff
@@ -278,10 +278,11 @@ object Task {
 
   def tasksById(tasks: Iterable[Task]): Map[Task.Id, Task] = tasks.iterator.map(task => task.taskId -> task).toMap
 
-  case class Id(idString: String) {
+  case class Id(idString: String) extends Comparable[Id] {
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/task/Task.scala]: Nit: `Ordered[Id]` would also give you equality operators.

Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/task/Task.scala]: BTW: why we need ordering for Id?

File: src/main/scala/mesosphere/marathon/upgrade/TaskReplaceActor.scala [hunk 8]
```diff
@@ -169,9 +163,50 @@ class TaskReplaceActor(
...
 
   case object RetryKills
+
+  /** Encapsulates the logic how to get a Restart going */
+  private[upgrade] case class RestartStrategy(nrToKillImmediately: Int, maxCapacity: Int)
+
+  private[upgrade] def computeRestartStrategy(app: AppDefinition, runningTasksCount: Int): RestartStrategy = {
+    // in addition to an app definition which passed validation, we require:
+    require(app.instances > 0, s"instances must be > 0 but is ${app.instances}")
+    require(runningTasksCount >= 0, s"running task count must be >=0 but is $runningTasksCount")
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/upgrade/TaskReplaceActor.scala]: Not sure if this requirement is valid:
- deploy application with n tasks
- the deployment is successful
- all tasks fail, all restart attempts fail as well
- we deploy a new version at exactly a time all tasks are gone

File: src/main/scala/mesosphere/marathon/upgrade/TaskReplaceActor.scala [hunk 9]
```diff
@@ -169,9 +163,50 @@ class TaskReplaceActor(
...
+        log.info(s"maxCapacity == minHealthy: Allow temporary over-capacity of one task to allow restarting")
+        maxCapacity += 1
+      }
+    }
+
+    log.info(s"For minimumHealthCapacity ${app.upgradeStrategy.minimumHealthCapacity} of ${app.id.toString} leave " +
+      s"$minHealthy tasks running, maximum capacity $maxCapacity, killing $nrToKillImmediately of " +
+      s"$runningTasksCount running tasks immediately")
+
+    assume(nrToKillImmediately >= 0, s"nrToKillImmediately must be >=0 but is $nrToKillImmediately")
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/upgrade/TaskReplaceActor.scala]: If the requirement above is not true, than also this assume would not hold.

**Comment by aquamatthias** [comment]
@kolloch Looks very good to me - especially the green box above. Thanks!
Please squash your commits and I will merge.

File: src/main/scala/mesosphere/marathon/core/launcher/impl/OfferProcessorImpl.scala (hunk 6 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/core/launcher/impl/OfferProcessorImpl.scala]: ok

File: src/main/scala/mesosphere/marathon/core/task/Task.scala (hunk 7 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/core/task/Task.scala]: Nice, I didn't really think of `Ordered`.

I think that it is always nice to be able to sort things, e.g. for reproducibility.

File: src/main/scala/mesosphere/marathon/upgrade/TaskReplaceActor.scala (hunk 9 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/upgrade/TaskReplaceActor.scala]: No, we cannot. It also depends on the number of running tasks.

E.g. if we have 3 running tasks, and a min health capacity of 4 and a max capacity of 4, we still would not need to kill a task.

Comment (kolloch) [inline src/main/scala/mesosphere/marathon/upgrade/TaskReplaceActor.scala]: We could assume something like `minHealthy < maxCapacity || runningTasksCount - nrToKillImmediately < maxCapacity`

File: src/main/scala/mesosphere/marathon/upgrade/TaskReplaceActor.scala [hunk 10]
```diff
@@ -174,23 +174,38 @@ object TaskReplaceActor {
...
 
     log.info(s"For minimumHealthCapacity ${app.upgradeStrategy.minimumHealthCapacity} of ${app.id.toString} leave " +
-      s"$minHealthy tasks running, maximum capacity $maxCapacity, killing $nrToKillImmediately tasks immediately")
+      s"$minHealthy tasks running, maximum capacity $maxCapacity, killing $nrToKillImmediately of " +
+      s"$runningTasksCount running tasks immediately")
+
+    assume(nrToKillImmediately >= 0, s"nrToKillImmediately must be >=0 but is $nrToKillImmediately")
+    assume(maxCapacity > 0, s"maxCapacity must be >0 but is $maxCapacity")
+    def canStartNewTasks: Boolean = minHealthy < maxCapacity || runningTasksCount - nrToKillImmediately < maxCapacity
+    assume(canStartNewTasks, s"must be able to start new tasks")
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/upgrade/TaskReplaceActor.scala]: @aquamatthias does that look good to you?

**Comment by kolloch** [comment]
I split up and squashed the commits along authors and topics.

The integration tests fail on teamcity because they cannot resolve a necessary GPG key. On my local machine, I could get beyond that step. Not sure how to proceed:

* Hope that it is a temporary TeamCity network-related problem and wait?
* Investigate, trying alternatives.

It is annoying to debug if we cannot reproduce it locally. We had similar problems already in the past.

**Comment by kolloch** [comment]
aah, the last teamcity build moved beyond that error.

**Comment by kolloch** [comment]
Ok, there was another sporadic error which looks similar to the ones that I tried to fix.

I think that the code in this PR is an improvement anyway. I will try to reproduce that error locally with extended debug settings, again.

In the mean time I would suggest to

* either merge this PR completely
* or to separate the last commit that tries to address the error seen in TeamCity but which apparently is not complete and merge the rest

**Comment by aquamatthias** [comment]
Thanks!
