### PR TITLE
Fixes #5211 by defining the jersey annotated methods explicitly.

### LINKED ISSUE #5211: Marathon v1.4.0 /v2/apps PUT REST API Error
Marathon v1.4.0 on Ubuntu 14.04 REST API /v2/apps PUT does not seem to work. It always returns error status 422.

Try starting a simple new app: 
> [
  {
    "id": "/test/sleep120",
    "cmd": "sleep 120",
    "cpus": 0.3,
    "instances": 2,
    "mem": 9
  }
]

And the return message (status 422):
> {
  "message": null
}

The easiest way to reproduce this is with the Marathon UI API Console:
    [http://localhost:8080/api-console/index.html](url)
And use the /v2/apps PUT API.

This same job, /test/sleep120, works if it's started using the POST API.

The only error message I see is in syslog 

> marathon[19778]: [2017-02-18 19:09:09,304] ERROR Exception while processing request (mesosphere.marathon.api.MarathonExceptionMapper$$EnhancerByGuice$$9833dc0d:qtp1923232046-38)
marathon[19778]: java.lang.IllegalArgumentException: null
marathon[19778]: #011at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
marathon[19778]: #011at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
marathon[19778]: #011at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
marathon[19778]: #011at java.lang.reflect.Method.invoke(Method.java:498)
 marathon[19778]: #011at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
marathon[19778]: #011at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
marathon[19778]: #011at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
. . .
marathon[19778]: #011at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
marathon[19778]: #011at mesosphere.marathon.api.CacheDisablingFilter.doFilter(CacheDisablingFilter.scala:18)
marathon[19778]: #011at mesosphere.marathon.api.CacheDisablingFilter$$EnhancerByGuice$$bbaeb0a8.CGLIB$doFilter$0(<generated>)
marathon[19778]: #011at mesosphere.marathon.api.CacheDisablingFilter$$EnhancerByGuice$$bbaeb0a8$$FastClassByGuice$$ccb95931.invoke(<generated>)
. . .

### PR DESCRIPTION
**Pull request by unterstein**
With the newly introduced `PATCH` semantic, we introduced a misleading method declaration which is not resolvable for jersey. Therefore this logic was restructured and methods are defined explicitly.
Reverted #5202 by the way.

Test Plan:
```
sbt "integration:test"
```

Change summary:

Status before:
```
replace(... , allowCreation: Boolean = true) {
  // all the logic
}

patch(...) {
  replace(... , allowCreation = false)
}
```

Status after:
```
replace(...) {
  update(... , allowCreation = true)
}

patch(...) {
  update(... , allowCreation = false)
}

private update(...) {
  // all the logic
}
```

### CODE REVIEW

File: src/test/scala/mesosphere/marathon/integration/AppDeployIntegrationTest.scala [hunk 1]
```diff
@@ -17,7 +17,6 @@ import scala.concurrent.duration._
 import scala.util.control.NonFatal
 
 @IntegrationTest
-@UnstableTest
```
Comment (janisz) [inline src/test/scala/mesosphere/marathon/integration/AppDeployIntegrationTest.scala]: I told you https://github.com/mesosphere/marathon/pull/5183#pullrequestreview-22304211

Comment (unterstein) [inline src/test/scala/mesosphere/marathon/integration/AppDeployIntegrationTest.scala]: 😢 🐼
