### PR TITLE
Override Timestamp hashCode for consistent hashing

### LINKED ISSUE #1082: firstSuccess in health checks is incorrect
I'm running master, as usual.

First success for task in ui is reported at `13:47:32` (UTC+4 #1038):

screen shot 2015-01-23 at 12 51 53

But in logs first success happened much faster:

```
[2015-01-23 09:43:45,927] INFO Received status update for task topface_prod-test_app.352fb707-a2e4-11e4-b8c3-56847afe9799: TASK_RUNNING () (mesosphere.marathon.MarathonScheduler:148)
[INFO] [01/23/2015 09:43:47.680] [marathon-akka.actor.default-dispatcher-19] [akka://marathon/user/$r] Received health result: [Unhealthy(topface_prod-test_app.352fb707-a2e4-11e4-b8c3-56847afe9799,2015-01-23T09:42:55.010Z,ConnectException: Connection refused,2015-01-23T09:43:47.680Z)]
[INFO] [01/23/2015 09:43:49.700] [marathon-akka.actor.default-dispatcher-18] [akka://marathon/user/$r] Received health result: [Unhealthy(topface_prod-test_app.352fb707-a2e4-11e4-b8c3-56847afe9799,2015-01-23T09:42:55.010Z,ConnectException: Connection refused,2015-01-23T09:43:49.700Z)]
[INFO] [01/23/2015 09:43:51.720] [marathon-akka.actor.default-dispatcher-5] [akka://marathon/user/$r] Received health result: [Unhealthy(topface_prod-test_app.352fb707-a2e4-11e4-b8c3-56847afe9799,2015-01-23T09:42:55.010Z,ConnectException: Connection refused,2015-01-23T09:43:51.720Z)]
[INFO] [01/23/2015 09:43:53.742] [marathon-akka.actor.default-dispatcher-23] [akka://marathon/user/$r] Received health result: [Healthy(topface_prod-test_app.352fb707-a2e4-11e4-b8c3-56847afe9799,2015-01-23T09:42:55.010Z,2015-01-23T09:43:53.741Z)]
[INFO] [01/23/2015 09:43:53.742] [marathon-akka.actor.default-dispatcher-2] [akka://marathon/user/MarathonScheduler/$a/UpgradeManager/f20d2493-45ab-44e3-8ba1-2c5d1437503e/$a] Killing old task topface_prod-test_app.e0b75ff8-a2e2-11e4-b8c3-56847afe9799 because topface_prod-test_app.352fb707-a2e4-11e4-b8c3-56847afe9799 became reachable
[INFO] [01/23/2015 09:43:55.762] [marathon-akka.actor.default-dispatcher-4] [akka://marathon/user/$r] Received health result: [Healthy(topface_prod-test_app.352fb707-a2e4-11e4-b8c3-56847afe9799,2015-01-23T09:42:55.010Z,2015-01-23T09:43:55.761Z)]
[INFO] [01/23/2015 09:43:57.780] [marathon-akka.actor.default-dispatcher-21] [akka://marathon/user/$r] Received health result: [Healthy(topface_prod-test_app.352fb707-a2e4-11e4-b8c3-56847afe9799,2015-01-23T09:42:55.010Z,2015-01-23T09:43:57.780Z)]
[INFO] [01/23/2015 09:43:59.800] [marathon-akka.actor.default-dispatcher-12] [akka://marathon/user/$r] Received health result: [Healthy(topface_prod-test_app.352fb707-a2e4-11e4-b8c3-56847afe9799,2015-01-23T09:42:55.010Z,2015-01-23T09:43:59.800Z)]
```

The last started task in this app was actually started at ~13:47. It looks like health checks are not saved until all tasks are running. In UI health check bullet is gray before each task is running in current revision.

### PR DESCRIPTION
**Pull request by sttts**
Timestamp's hashCode was based on the parameter dateTime which might have
a timezone != UTC. The consequence:

  val t = Timestamp.now
  t.hashCode != Timestamp(t.toString).hashCode

This patch overrides hashCode to use the UTC normalized time variable of the
Timestamp case class.

This probably fixes #1082

### CODE REVIEW

File: src/main/scala/mesosphere/marathon/state/Timestamp.scala [hunk 1]
```diff
@@ -15,6 +15,8 @@ case class Timestamp(dateTime: DateTime) extends Ordered[Timestamp] {
     case _               => false
   }
 
+  override def hashCode: Int = time.hashCode
```
Comment (ConnorDoyle) [inline src/main/scala/mesosphere/marathon/state/Timestamp.scala]: Excellent.  See: https://github.com/JodaOrg/joda-time/blob/fd323b4a8fa05348c67bdace8dde380ffa7b7435/src/main/java/org/joda/time/base/AbstractInstant.java#L276

Comment (ConnorDoyle) [inline src/main/scala/mesosphere/marathon/state/Timestamp.scala]: Could you add a comment to make it explicit that we depend upon `time` being a UTC DateTime to uphold the `equals`/`hashCode` contract?

Comment (sttts) [inline src/main/scala/mesosphere/marathon/state/Timestamp.scala]: Sure.

**Comment by sttts** [comment]
Was wondering whether it would be cleaner to move the UTC conversion into the apply constructors and turn the current UTC time into the case class parameter.

```Scala
case class Timestamp(utcDateTime: DateTime) extends Ordered[Timestamp]

object Timestamp {
   def apply(time: String): Timestamp = Timestamp(
      DateTime.parse(time).toDateTime(DateTimeZone.UTC)
   )
}
```

Then we can probably get rid of most of the overrides in the case class.

**Comment by ConnorDoyle** [comment]
@sttts, we could map the time zone in the companion's apply method.  We'd also have to make the constructor private to disallow invalid instances from being built.  IMO, it is quite clear as written.  Let's leave a refactor out of this bugfix for a subsequent PR.

**Comment by ConnorDoyle** [comment]
Thanks! :shipit:

**Comment by bobrik** [comment]
:confetti_ball: :tada:
