### PR TITLE
fixes #1195 - Fix validation logic for AppDefinition

### LINKED ISSUE #1195: Validation logic for xor(cmd, args) is broken when container is set
When a container is set, both, cmd and args can be supplied. This should not be possible.

### PR DESCRIPTION
**Pull request by drexin**

### CODE REVIEW

File: src/main/scala/mesosphere/marathon/api/validation/AppDefinitionValidator.scala [hunk 1]
```diff
@@ -7,16 +7,13 @@ import mesosphere.marathon.state.{ AppDefinition, Container }
...
-    (p || q) && (!p || !q)
-
   override def isValid(
     value: AppDefinition,
     context: ConstraintValidatorContext): Boolean = {
     val cmd = value.cmd.nonEmpty
     val args = value.args.nonEmpty
     val container = value.container.exists(_ != Container.Empty)
-    xor(cmd, args) || container
+    (cmd ^ args) || (!(cmd || args) && container)
```
Comment (ConnorDoyle) [inline src/main/scala/mesosphere/marathon/api/validation/AppDefinitionValidator.scala]: Cool, didn't know about the built-in boolean xor!  :+1:
