### PR TITLE
Fixes #3291 | Event subscriptions validation

### LINKED ISSUE #3291: Event subscriptions failing if one of them is not correct
It seems that if a host is not correct, marathon fails to send the subscriptions  to all the next nodes in the subscription list.
For example, if I have the next subscription list, where the second one is not correct: 
```
{"callbackUrls":["http://10.2.2.216:8000/api/marathon/event_callback","10.2.2.215:8000/api/marathon/event_callback","http://10.2.0.168:8000/api/marathon/event_callback"]}
```
The first host on the list is receiving the events and the third one is not receiving it.

I'm seeing this logs on marathon:
```
[2016-02-22 11:44:48,335] INFO Removing 981253ab-59f8-442d-a78a-d779c176fe05 from list of running deployments (mesosphere.marathon.upgrade.DeploymentManager:marathon-akka.actor.default-dispatcher-53)    [47/1520]
[2016-02-22 11:44:48,335] INFO Updated groups/apps according to deployment plan 981253ab-59f8-442d-a78a-d779c176fe05 (mesosphere.marathon.state.GroupManager:ForkJoinPool-2-worker-15)
spray.http.IllegalUriException: Illegal URI reference, unexpected character ':' at position 10: 
10.2.2.215:8000/api/marathon/event_callback
          ^
[2016-02-22 11:44:48,336] INFO POSTing to all endpoints. (mesosphere.marathon.event.http.HttpEventActor:marathon-akka.actor.default-dispatcher-53)
[2016-02-22 11:44:48,337] INFO Deployment acknowledged. Waiting to get processed:
DeploymentPlan 2016-02-22T11:44:48.299Z NO STEPS
 (mesosphere.marathon.state.GroupManager:ForkJoinPool-2-worker-15)
[2016-02-22 11:44:48,337] INFO 10.2.1.31 - - [22/Feb/2016:11:44:48 +0000] "PUT //10.2.0.13:8080/v2/apps//hello HTTP/1.1" 200 92 "http://xxxxxxxxxxxxxxx:8080/ui/" "Mozilla/5.0 (X11
; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0" 4 (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$b2a9f498:qtp697240075-30)
[2016-02-22 11:44:48,340] INFO Sending POST to:http://10.2.2.216:8000/api/marathon/event_callback (mesosphere.marathon.event.http.HttpEventActor:marathon-akka.actor.default-dispatcher-53)

        at spray.http.Uri$.fail(Uri.scala:775)
        at spray.http.parser.UriParser.complete(UriParser.scala:429)
[2016-02-22 11:44:48,344] INFO Sending POST to:10.2.2.215:8000/api/marathon/event_callback (mesosphere.marathon.event.http.HttpEventActor:marathon-akka.actor.default-dispatcher-53)
[2016-02-22 11:44:48,346] INFO POSTing to all endpoints. (mesosphere.marathon.event.http.HttpEventActor:marathon-akka.actor.default-dispatcher-53)
        at spray.http.parser.UriParser.parseReference(UriParser.scala:60)
        at spray.http.Uri$.apply(Uri.scala:231)
        at spray.http.Uri$.apply(Uri.scala:203)
        at spray.httpx.RequestBuilding$RequestBuilder.apply(RequestBuilding.scala:36)
[2016-02-22 11:44:48,349] INFO Sending POST to:http://10.2.2.216:8000/api/marathon/event_callback (mesosphere.marathon.event.http.HttpEventActor:marathon-akka.actor.default-dispatcher-53)
        at spray.httpx.RequestBuilding$RequestBuilder.apply(RequestBuilding.scala:35)
        at mesosphere.marathon.event.http.HttpEventActor.post(HttpEventActor.scala:94)
        at mesosphere.marathon.event.http.HttpEventActor$$anonfun$broadcast$1$$anonfun$apply$1.apply(HttpEventActor.scala:86)
        at mesosphere.marathon.event.http.HttpEventActor$$anonfun$broadcast$1$$anonfun$apply$1.apply(HttpEventActor.scala:86)
        at scala.collection.immutable.Set$Set3.foreach(Set.scala:145)
        at mesosphere.marathon.event.http.HttpEventActor$$anonfun$broadcast$1.apply(HttpEventActor.scala:86)
        at mesosphere.marathon.event.http.HttpEventActor$$anonfun$broadcast$1.apply(HttpEventActor.scala:78)
        at scala.util.Success.foreach(Try.scala:236)
        at scala.concurrent.Future$$anonfun$foreach$1.apply(Future.scala:204)
        at scala.concurrent.Future$$anonfun$foreach$1.apply(Future.scala:204)
[2016-02-22 11:44:48,354] INFO Sending POST to:10.2.2.215:8000/api/marathon/event_callback (mesosphere.marathon.event.http.HttpEventActor:marathon-akka.actor.default-dispatcher-53)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
spray.http.IllegalUriException: Illegal URI reference, unexpected character ':' at position 10: 
10.2.2.215:8000/api/marathon/event_callback
          ^
[2016-02-22 11:44:48,360] INFO POSTing to all endpoints. (mesosphere.marathon.event.http.HttpEventActor:marathon-akka.actor.default-dispatcher-53)
[2016-02-22 11:44:48,361] INFO Sending POST to:http://10.2.2.216:8000/api/marathon/event_callback (mesosphere.marathon.event.http.HttpEventActor:marathon-akka.actor.default-dispatcher-53)

        at spray.http.Uri$.fail(Uri.scala:775)
        at spray.http.parser.UriParser.complete(UriParser.scala:429)
        at spray.http.parser.UriParser.parseReference(UriParser.scala:60)
        at spray.http.Uri$.apply(Uri.scala:231)
        at spray.http.Uri$.apply(Uri.scala:203)
        at spray.httpx.RequestBuilding$RequestBuilder.apply(RequestBuilding.scala:36)
        at spray.httpx.RequestBuilding$RequestBuilder.apply(RequestBuilding.scala:35)
        at mesosphere.marathon.event.http.HttpEventActor.post(HttpEventActor.scala:94)
        at mesosphere.marathon.event.http.HttpEventActor$$anonfun$broadcast$1$$anonfun$apply$1.apply(HttpEventActor.scala:86)
        at mesosphere.marathon.event.http.HttpEventActor$$anonfun$broadcast$1$$anonfun$apply$1.apply(HttpEventActor.scala:86)
        at scala.collection.immutable.Set$Set3.foreach(Set.scala:145)
        at mesosphere.marathon.event.http.HttpEventActor$$anonfun$broadcast$1.apply(HttpEventActor.scala:86)
        at mesosphere.marathon.event.http.HttpEventActor$$anonfun$broadcast$1.apply(HttpEventActor.scala:78)
        at scala.util.Success.foreach(Try.scala:236)
        at scala.concurrent.Future$$anonfun$foreach$1.apply(Future.scala:204)
        at scala.concurrent.Future$$anonfun$foreach$1.apply(Future.scala:204)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2016-02-22 11:44:48,365] INFO Sending POST to:10.2.2.215:8000/api/marathon/event_callback (mesosphere.marathon.event.http.HttpEventActor:marathon-akka.actor.default-dispatcher-49)
spray.http.IllegalUriException: Illegal URI reference, unexpected character ':' at position 10: 
10.2.2.215:8000/api/marathon/event_callback
          ^
[2016-02-22 11:44:48,373] INFO 10.2.2.216 - - [22/Feb/2016:11:44:48 +0000] "GET //10.2.0.13:8080/v2/apps HTTP/1.1" 200 935 "-" "Go 1.1 package http" 2 (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$b2a9
f498:qtp697240075-32)

        at spray.http.Uri$.fail(Uri.scala:775)
        at spray.http.parser.UriParser.complete(UriParser.scala:429)
        at spray.http.parser.UriParser.parseReference(UriParser.scala:60)
        at spray.http.Uri$.apply(Uri.scala:231)
        at spray.http.Uri$.apply(Uri.scala:203)
        at spray.httpx.RequestBuilding$RequestBuilder.apply(RequestBuilding.scala:36)
        at spray.httpx.RequestBuilding$RequestBuilder.apply(RequestBuilding.scala:35)
        at mesosphere.marathon.event.http.HttpEventActor.post(HttpEventActor.scala:94)
        at mesosphere.marathon.event.http.HttpEventActor$$anonfun$broadcast$1$$anonfun$apply$1.apply(HttpEventActor.scala:86)
        at mesosphere.marathon.event.http.HttpEventActor$$anonfun$broadcast$1$$anonfun$apply$1.apply(HttpEventActor.scala:86)
        at scala.collection.immutable.Set$Set3.foreach(Set.scala:145)
        at mesosphere.marathon.event.http.HttpEventActor$$anonfun$broadcast$1.apply(HttpEventActor.scala:86)
        at mesosphere.marathon.event.http.HttpEventActor$$anonfun$broadcast$1.apply(HttpEventActor.scala:78)
        at scala.util.Success.foreach(Try.scala:236)
        at scala.concurrent.Future$$anonfun$foreach$1.apply(Future.scala:204)
        at scala.concurrent.Future$$anonfun$foreach$1.apply(Future.scala:204)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

### PR DESCRIPTION
**Pull request by janisz**

### CODE REVIEW

File: src/main/scala/mesosphere/marathon/api/v2/EventSubscriptionsResource.scala [hunk 1]
```diff
@@ -35,7 +36,9 @@ class EventSubscriptionsResource @Inject() (val config: MarathonConf) extends Re
   @Timed
   def subscribe(@Context req: HttpServletRequest, @QueryParam("callbackUrl") callbackUrl: String): Response = {
     validateSubscriptionService()
-    val future: Future[MarathonEvent] = service.handleSubscriptionEvent(Subscribe(req.getRemoteAddr, callbackUrl))
+    validateUrl(callbackUrl)
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/api/v2/EventSubscriptionsResource.scala]: We moved to a validation API (example: https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/state/PortDefinition.scala#L15)
Do you think you can use that as well?

File: src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala [hunk 2]
```diff
@@ -96,7 +96,13 @@ class HttpEventActor(conf: HttpEventConfiguration,
     //remove all unsubscribed callback listener
     limiter = limiter.filterKeys(subscribers.urls).iterator.toMap.withDefaultValue(NoLimit)
     metrics.skippedCallbacks.mark(limited.size)
-    active.foreach(post(_, event, self))
+    active.foreach(url => Try(post(url, event, self)) match {
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: The post method itself will send a NotificationFailed in this case. 
Do I miss something?

File: src/main/scala/mesosphere/marathon/event/http/HttpEventModule.scala [hunk 3]
```diff
@@ -17,13 +17,15 @@ import org.slf4j.LoggerFactory
...
 import scala.language.postfixOps
+import scala.util.Try
 
 trait HttpEventConfiguration extends ScallopConf {
 
   lazy val httpEventEndpoints = opt[String]("http_endpoints",
     descr = "The URLs of the event endpoints added to the current list of subscribers on startup. " +
       "You can manage this list during runtime by using the /v2/eventSubscriptions API endpoint.",
     required = false,
+    validate = { str => Try(str.split(',').map(url => new URL(url.trim))).isSuccess },
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventModule.scala]: You could use `foreach` instead of map, since you don't need the result.

**Comment by aquamatthias** [comment]
@janisz Thanks for this PR!
I added a couple of comments.

File: src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala (hunk 2 above)
Comment (janisz) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: > [If the given string is not a valid URI the method throws an `IllegalUriException`.](https://github.com/spray/spray/blob/master/spray-http/src/main/scala/spray/http/Uri.scala#L210)

After merging this PR it will be impossible to set invalid callback but it could be set before and I want to prevent this old entry to stop other events.

File: src/main/scala/mesosphere/marathon/api/v2/EventSubscriptionsResource.scala (hunk 1 above)
Comment (janisz) [inline src/main/scala/mesosphere/marathon/api/v2/EventSubscriptionsResource.scala]: I moved validation function to `src/main/scala/mesosphere/marathon/api/v2/Validation.scala` and reused it in `src/main/scala/mesosphere/marathon/event/http/HttpEventModule.scala`.

File: src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala (hunk 2 above)
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: Makes sense.

**Comment by aquamatthias** [comment]
Thanks!
