### PR TITLE
Fixes #3957 - Load previously stored health status when becoming leader

### LINKED ISSUE #3957: COMMAND HealthChecks removed on mesos-master restart/issue
COMMAND Health Checks are being removed (i.e. `INFO Removing health check for app`) and never re-created when something happens to the mesos-master. I have seen this with both a restart of the mesos-master and also under less controlled situations such as a leader re-election or network issues.

To reproduce:

1) Create an App with a COMMAND Health Check
2) Restart mesos-master
3) grep marathon log for `Removing health check`

Although `addAllFor` and subsequently `add` is called (which you can see int he logs: `INFO Adding health check for app`) No health check data is ever available either via the UI (the good old grey bar of doom) or via the JSON return via the API.

The HTTP and TCP Health Checks return successfully but the only way to re-establish the COMMAND Health Checks is to restart the Apps.

Using:
Mesos: 0.28.0
Marathon: 1.1.1

### PR DESCRIPTION
**Pull request by gkleiman**
See #4094 for some context.

### CODE REVIEW

File: src/main/scala/mesosphere/marathon/upgrade/DeploymentActor.scala [hunk 1]
```diff
@@ -88,7 +88,8 @@ private class DeploymentActor(
       eventBus.publish(status)
 
       val futures = step.actions.map { action =>
-        healthCheckManager.addAllFor(action.app) // ensure health check actors are in place before tasks are launched
+        // ensure health check actors are in place before tasks are launched
+        healthCheckManager.addAllFor(action.app, Seq.empty)
```
Comment (jdef) [inline src/main/scala/mesosphere/marathon/upgrade/DeploymentActor.scala]: the "ensure ... are in place" semantics depend on a side-affect of addAllFor. would prefer to see a MarathonHealthCheckManager `prepareFor(...)` or something (and maybe that impl would invoke addAllFor, hiding the impl detail from DeploymentActor). Would make for a cleaner interface between deployments and health checks.

File: src/main/scala/mesosphere/marathon/core/health/impl/MarathonHealthCheckManager.scala [hunk 2]
```diff
@@ -112,13 +126,26 @@ class MarathonHealthCheckManager(
...
+          }
+      }
+
+    appRepository.get(appId).flatMap {
       case None => Future(())
       case Some(app) =>
         log.info(s"reconcile [$appId] with latest version [${app.version}]")
 
         val tasks: Iterable[Task] = taskTracker.appTasksSync(app.id)
+        val tasksByVersion = groupTasksByVersion(tasks)
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/health/impl/MarathonHealthCheckManager.scala]: Why do we need groupByVersion? Isn't that a simple filter for task.version>=app.version?

**Comment by aquamatthias** [comment]
@gkleiman One question regarding groupBy. Have you tested this fix?

File: src/main/scala/mesosphere/marathon/core/health/impl/MarathonHealthCheckManager.scala (hunk 2 above)
Comment (gkleiman) [inline src/main/scala/mesosphere/marathon/core/health/impl/MarathonHealthCheckManager.scala]: I think that we do need it, because Marathon starts a HealthCheckActor per app version with active tasks, see line #179 (https://github.com/mesosphere/marathon/pull/4311/files#diff-82c63be54fc7bbda204fdfde44104e48R179).

**Comment by gkleiman** [comment]
@aquamatthias I answered to your regarding the groupBy.

I updated the tests and also tested the patch manually, by creating an app with a COMMAND health check, waiting until it's healthy and the restarting the Marathon leader.

File: src/main/scala/mesosphere/marathon/core/health/HealthResult.scala [hunk 3]
```diff
@@ -7,15 +7,18 @@ sealed trait HealthResult {
...
   def time: Timestamp
+  def publishEvent: Boolean
 }
 
 case class Healthy(
   taskId: Task.Id,
   version: Timestamp,
-  time: Timestamp = Timestamp.now()) extends HealthResult
+  time: Timestamp = Timestamp.now(),
+  publishEvent: Boolean = true) extends HealthResult
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/health/HealthResult.scala]: Not a fan of adding this to the healthy/unhealthy state. Given the current implementation, this is the smallest invasive change. We need to refactor the health check manager to improve.

**Comment by aquamatthias** [comment]
@gkleiman Thanks. Waiting for the tests to become green.

**Comment by gkleiman** [comment]
@aquamatthias they're green =) I'll try to backport this to v1.1

**Comment by aquamatthias** [comment]
Thanks. backport to 1.1 would be great

**Comment by jdef** [comment]
what about cherry-picking into 1.3?

**Comment by aquamatthias** [comment]
@jdef right. once we have 1.1 it should be easy to do it?
@gkleiman wdyt?

**Comment by ottoyiu** [comment]
is the fix cherry-picked into the 1.1 branch? I see 347d9bb commit on it, but an integration test is failing which I can't pinpoint why...
