### PR TITLE
Fixes #2543 - relative path in application dependencies within a group.

### LINKED ISSUE #2543: Allow relative application dependencies
Dependencies in groups can be absolute or relative.
Dependencies in apps have to be absolute.

Following example does not work as expected:
```json
{
    "id": "group-app-test",
    "apps": [
        {
            "id": "app-test01",
            "dependencies": [],
            ...
        },
        {
            "id": "app-test02",
            "dependencies": [],
            ...
        },
        {
            "id": "app-test03",
            "dependencies": ["app-test01", "app-test02"],
            ...
        },
        {
            "id": "app-test04",
            "dependencies": ["app-test03"],
            ...
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by alexanderweber**
Relative paths of application dependencies were converted to absolute paths up to the application it depended on. E.g.:
  app1: id="/apps/app1"
  app2: id="/apps/app2", dependencies="app1"
were converted to:
  app2: id="/apps/app2", dependencies="/apps/app2/app1"
This behaviour was changed to:
  app2: id="/apps/app2", dependencies="/apps/app1"
The relative path is now relative to the group and not to the application.

### CODE REVIEW

File: src/test/scala/mesosphere/marathon/api/v2/json/V2GroupUpdateTest.scala [hunk 1]
```diff
@@ -132,4 +132,25 @@ class V2GroupUpdateTest extends FunSuite with Matchers with GivenWhenThen {
...
+        "test-group".toPath,
+        Set(V2AppDefinition("test-app1".toPath),
+          V2AppDefinition("test-app2".toPath, dependencies = Set("test-app1".toPath)))
+      )
+    ))
+    When("The update is performed")
+    val result = update(V2Group(Group.empty), Timestamp.now()).toGroup()
+
+    Then("The update is applied correctly")
+    val apps = result.group("test-group".toRootPath)
```
Comment (aquamatthias) [inline src/test/scala/mesosphere/marathon/api/v2/json/V2GroupUpdateTest.scala]: The result of that is a group not apps. Please rename the val.

File: src/test/scala/mesosphere/marathon/api/v2/json/V2GroupUpdateTest.scala [hunk 2]
```diff
@@ -132,4 +132,25 @@ class V2GroupUpdateTest extends FunSuite with Matchers with GivenWhenThen {
...
+  test("Relative path of a dependency, should be relative to group and not to the app") {
+    Given("A group with two apps. Second app is dependend of first.")
+
+    val update = V2GroupUpdate(PathId.empty, Set.empty[V2AppDefinition], Set(
+      V2GroupUpdate(
+        "test-group".toPath,
+        Set(V2AppDefinition("test-app1".toPath),
+          V2AppDefinition("test-app2".toPath, dependencies = Set("test-app1".toPath)))
+      )
+    ))
```
Comment (aquamatthias) [inline src/test/scala/mesosphere/marathon/api/v2/json/V2GroupUpdateTest.scala]: Minor: Can you add a line feed, so we can easy distinguish Given/When/Then?

**Comment by aquamatthias** [comment]
Thanks! Looks good to me. 2 Minor issues. Please fix and I will merge.

File: src/test/scala/mesosphere/marathon/api/v2/json/V2GroupUpdateTest.scala (hunk 2 above)
Comment (alexanderweber) [inline src/test/scala/mesosphere/marathon/api/v2/json/V2GroupUpdateTest.scala]: I hope you meant the line feed before 'When'. I matched it up with the style of the other tests.

**Comment by aquamatthias** [comment]
@alexanderweber Thanks. Can you please squash the commits?

**Comment by alexanderweber** [comment]
@aquamatthias Sure, looks like this time the squash worked flawlessly.

**Comment by aquamatthias** [comment]
Thanks!
