### PR TITLE
Fixes #3241 - consistent JSON error output.

### LINKED ISSUE #3241: Serverside validation messages are inconsistent
There seem to be two kinds of error response objects when validation errors occur in the API:

Case 1) Generic errors
Case 2) Field-specific errors

**Case 1** errors trigger a `422` response with this structure:
```
{
  "message": "Object is not valid",
  "details": [
    {
      "attribute": "value",
      "error": "Groups and Applications may not have the same identifier: /hello"
    }
  ]
}
```
(side-note: `value` seems to be a placeholder for non-specific attribute paths)

**Case 2** errors trigger a `400` response with this structure:
```
{
  "message": "Invalid JSON",
  "details": [
    {
      "path": "/cpus",
      "errors": [
        "error.expected.jsnumber"
      ]
    }
  ]
}
```

I suggest the following result for consistency:

**Case 1)** `422`
```
{
  "message": "Object is not valid",
  "details": [
    {
      "path": "general",
      "errors": [
        "Groups and Applications may not have the same identifier: /hello"
      ]
    }
  ]
}
```

**Case 2)** `400`
Unchanged.

Please correct if I'm wrong and looking forward to hearing your thoughts on this.

### PR DESCRIPTION
**Pull request by alexanderweber**
Fixes #3241 applying following changes to JSON output of errors:

1. `attribute` field renamed to `path`
2. `error` field renamed to `errors`
3. `errors` field contains a list of errors caused by an attribute, which location can be found in `path`
4. root `path` information is no longer labeled as `value`, but as `self`
5. `.value` should never terminate a path (e.g. `apps[0].value` is replaced by `apps[0]`)
6. `"path": "self"` if there is no description about the point of failure at all

### CODE REVIEW

**Comment by alexanderweber** [comment]
@aquamatthias I did apply the changes we've been talking about in #3241. You can find the list of changes in the description of this PR. Glad to receive any feedback!
cc/ @pierlo-upitup

File: src/test/scala/mesosphere/marathon/api/v2/ModelValidationTest.scala [hunk 1]
```diff
@@ -74,6 +80,34 @@ class ModelValidationTest
...
 
+  test("Multiple errors within one field of a validator should be grouped into one array") {
+    val empty = ImportantTitle("")
+
+    validate(empty) match {
+      case Success => fail()
+      case f: Failure =>
+        val errors = (Json.toJson(f) \ "details").as[Seq[JsObject]]
+        errors should have size 1
+        (errors.head \ "path").as[String] should be("name")
```
Comment (aquamatthias) [inline src/test/scala/mesosphere/marathon/api/v2/ModelValidationTest.scala]: If we see self as top level object. Shouldn't it be `self.name` here?

File: src/test/scala/mesosphere/marathon/api/v2/ModelValidationTest.scala [hunk 2]
```diff
@@ -74,6 +80,34 @@ class ModelValidationTest
...
+      AppDefinition("/test/group1/valid".toPath, cmd = Some("foo")),
+      AppDefinition("/test/group1/invalid".toPath)
+    ))
+
+    validate(group) match {
+      case Success => fail()
+      case f: Failure =>
+        val errors = (Json.toJson(f) \ "details").as[Seq[JsObject]]
+        errors should have size 1
+        (errors.head \ "path").as[String] should be("apps[1]")
```
Comment (aquamatthias) [inline src/test/scala/mesosphere/marathon/api/v2/ModelValidationTest.scala]: Question: should the path be `self.groups[0].apps[1]` ?

**Comment by aquamatthias** [comment]
@alexanderweber questions about the goal - let's have a short discussion.

File: src/test/scala/mesosphere/marathon/api/v2/ModelValidationTest.scala (hunk 1 above)
Comment (alexanderweber) [inline src/test/scala/mesosphere/marathon/api/v2/ModelValidationTest.scala]: The way i got it last time is, that self appears if the error is on the top level only. Meaning if the error is in an attribute of the object, the path yields only the attribute. So self would appear as a standalone information, if the error is not in an attribute, but the object itself. I agree that prepending it in general is a coherent solution, if it does not confuse the user, I am also in for that.

File: src/test/scala/mesosphere/marathon/api/v2/ModelValidationTest.scala (hunk 2 above)
Comment (alexanderweber) [inline src/test/scala/mesosphere/marathon/api/v2/ModelValidationTest.scala]: The `self` part is described in the upper comment. Regarding `groups[0]` - there is only one group here, containing two apps. The validation is done on that group object, so there is no list of groups in it.

**Comment by alexanderweber** [comment]
@aquamatthias Sure thing, I left my note on both comments. Basically I am in for prepending `self.` in general in all error messages, as it is describing the error tree most accurately. Let me know if I should do the change.

File: src/test/scala/mesosphere/marathon/api/v2/ModelValidationTest.scala (hunk 1 above)
Comment (aquamatthias) [inline src/test/scala/mesosphere/marathon/api/v2/ModelValidationTest.scala]: @pierlo-upitup also interested in your opinion on that.

File: src/test/scala/mesosphere/marathon/api/v2/ModelValidationTest.scala (hunk 2 above)
Comment (aquamatthias) [inline src/test/scala/mesosphere/marathon/api/v2/ModelValidationTest.scala]: You are right - I looked into the group path, which is nested, but the object hierarchy is not.
Can you make an example with a more nested problem?

File: src/test/scala/mesosphere/marathon/api/v2/ModelValidationTest.scala (hunk 1 above)
Comment (pierlo-upitup) [inline src/test/scala/mesosphere/marathon/api/v2/ModelValidationTest.scala]: As @alexanderweber  wrote
> So self would appear as a standalone information, if the error is not in an attribute, but the object itself.

That's how I got it too. If we have precise information regarding which attribute failed validation, then we don't need `self`. What's described at point 6 makes absolute sense to me:

> "path": "self" if there is no description about the point of failure at all

Comment (pierlo-upitup) [inline src/test/scala/mesosphere/marathon/api/v2/ModelValidationTest.scala]: Also 

https://github.com/mesosphere/marathon/issues/3241#issuecomment-184762112

File: src/test/scala/mesosphere/marathon/api/v2/ModelValidationTest.scala (hunk 2 above)
Comment (alexanderweber) [inline src/test/scala/mesosphere/marathon/api/v2/ModelValidationTest.scala]: Sure, I added a depth level to the example above.

**Comment by alexanderweber** [comment]
@aquamatthias I left it the way Pierluigi agreed on it and extended the test in terms of nesting. Let me know if I missed something important out.

**Comment by aquamatthias** [comment]
@alexanderweber Thanks!

**Comment by aquamatthias** [comment]
@pierlo-upitup can you please retest?

**Comment by pierlo-upitup** [comment]
Thanks, opening an issue https://github.com/mesosphere/marathon/issues/3337

**Comment by pierlo-upitup** [comment]
@alexanderweber thanks for this. 

@aquamatthias  question: doesn't this require an update to the docs? 

screen shot 2016-02-29 at 12 37 04

**Comment by alexanderweber** [comment]
Thanks for pointing that out. Docs are adjusted in #3387.
