### PR TITLE
Actually embedding tasks in /v2/apps?embed=apps.tasks

### LINKED ISSUE #1041: embed=apps.tasks on /v2/apps doesn't return tasks
The apps list API call doesn't not return app enriched with their tasks when requested, according to the embed parameter. 

To reproduce, call:
`curl -v http://master-0:8080/v2/apps?embed=apps.tasks`

Looking at `src/main/scala/mesosphere/marathon/api/v2/AppsResource.scala`, it seems that line 56 should be changed from 
```scala
          WithTaskCountsAndDeploymentsWrites.writes(enrichedApp)
```
to 
```scala
          WithTasksAndDeploymentsWrites.writes(enrichedApp)
```

I'm seeing this on the mesosphere-built Marathon 0.7.6, but the source suggests the problem as recently as 4d80bf4cc74562c2cd312902621e57cc08a2546f

The current workaround is simply to query with `embed=apps.failures`

### PR DESCRIPTION
**Pull request by bobrik**
Closes #1041, thanks @cgbaker!

### CODE REVIEW

File: src/main/scala/mesosphere/marathon/api/v2/AppsResource.scala [hunk 1]
```diff
@@ -53,7 +53,7 @@ class AppsResource @Inject() (
       case EmbedTasks =>
         apps.map { app =>
           val enrichedApp = app.withTasksAndDeployments(enrichedTasks(app), runningDeployments)
-          WithTaskCountsAndDeploymentsWrites.writes(enrichedApp)
+          WithTasksAndDeploymentsWrites.writes(enrichedApp)
```
Comment (ConnorDoyle) [inline src/main/scala/mesosphere/marathon/api/v2/AppsResource.scala]: :+1:

**Comment by drexin** [comment]
:shipit:
