### PR TITLE
Fixes #2130 - Store task failures in Zookeeper

### LINKED ISSUE #2130: Last task failures are not persisted
The `TaskFailureRepository` references an `EntityStore` but doesn't use it. It uses an in-memory map instead to save the last task failures. Even though, the last task failures are not the most important state, this can still lead to strange behavior on fail over or restart when API consumers see the "lastTaskFailure" disappear.

### PR DESCRIPTION
**Pull request by kolloch**

### CODE REVIEW

**Comment by kolloch** [comment]
I wanted to move this to 0.12 but it was so easy to write tests for this that I proceeded.

File: src/main/scala/mesosphere/marathon/state/TaskFailureRepository.scala [hunk 1]
```diff
@@ -1,17 +1,20 @@
...
+class TaskFailureRepository(
+  protected val store: EntityStore[TaskFailure],
+  protected val maxVersions: Option[Int] = Some(1),
+  protected val metrics: Metrics)
+    extends EntityRepository[TaskFailure] {
 
-  def store(id: PathId, value: TaskFailure): Unit =
-    synchronized { taskFailures(id) = value }
+  def store(id: PathId, value: TaskFailure): Future[TaskFailure] =
+    super.storeWithVersion(id.safePath, value.version, value)
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/state/TaskFailureRepository.scala]: Why do we store versions of a failure? 
Do we store only the last failure? (Should that be reflected in the class name?)
Should there be one entry per application (and version?) ?

File: src/test/scala/mesosphere/marathon/state/TaskFailureRepositoryTest.scala [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+
+    And("fetch it")
+    val readFailure = f.taskFailureRepo.current(PathId("/some/app")).futureValue
+
+    Then("the result is None")
+    readFailure should be(None)
+  }
+
+  class Fixture {
+    lazy val inMemoryStore = new InMemoryStore()
```
Comment (aquamatthias) [inline src/test/scala/mesosphere/marathon/state/TaskFailureRepositoryTest.scala]: Debatable if this should be run as unit or integration test...

File: src/main/scala/mesosphere/marathon/state/MarathonStore.scala [hunk 3]
```diff
@@ -15,7 +15,7 @@ class MarathonStore[S <: MarathonState[_, S]](
     store: PersistentStore,
     metrics: Metrics,
     newState: () => S,
-    prefix: String = "app:")(implicit ct: ClassTag[S]) extends EntityStore[S] {
+    prefix: String)(implicit ct: ClassTag[S]) extends EntityStore[S] {
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/state/MarathonStore.scala]: The default really was wrong...

**Comment by aquamatthias** [comment]
Generally is looking good. Made some comments.

File: src/test/scala/mesosphere/marathon/state/TaskFailureRepositoryTest.scala (hunk 2 above)
Comment (kolloch) [inline src/test/scala/mesosphere/marathon/state/TaskFailureRepositoryTest.scala]: It's fast. You do not need zookeeper or mesos. So why not always run it?

What do you think?

File: src/main/scala/mesosphere/marathon/state/TaskFailureRepository.scala (hunk 1 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/state/TaskFailureRepository.scala]: We only expose one task failure in our API, so in theory we could just store that.

All our stores are "versioned" so I just implemented it like this. Our current API of the `EntityRepository` only supports "versioned" stores.

But you are right, these are not really versions. 

I don't feel that we should persist the lastTaskFailure for every app version we retain. This would be quite some effort (synchronizing this with the versions of the AppRepo etc) but wouldn't have such great effect. The lastTaskFailure itself contains information about the version of the task.

You are asking a lot of (valuable) questions without providing your opinion. What do you think is best?

These are the options I see:

A) Leave it as is. There is a technically unnecessary overhead for versioning, even though we do not use the different versions.
B) Extend the EntityRepository to support unversioned storage and use that.
C) Use the an `EntityStore` directly.

I think that A) might lead to performance problems in load situations but otherwise OK.

B) is probably needed for a better task storage anyway (we do not want to version our task infos, do we?)

C) is ugly.

**Comment by kolloch** [comment]
I changed it to storing just one version per app.

File: src/test/scala/mesosphere/marathon/state/TaskFailureRepositoryTest.scala (hunk 2 above)
Comment (aquamatthias) [inline src/test/scala/mesosphere/marathon/state/TaskFailureRepositoryTest.scala]: I agree it's fast.

File: src/main/scala/mesosphere/marathon/state/TaskFailureRepository.scala [hunk 4]
```diff
@@ -1,17 +1,20 @@
...
+class TaskFailureRepository(
+  protected val store: EntityStore[TaskFailure],
+  protected val maxVersions: Option[Int] = Some(1),
+  protected val metrics: Metrics)
+    extends EntityRepository[TaskFailure] {
 
-  def store(id: PathId, value: TaskFailure): Unit =
-    synchronized { taskFailures(id) = value }
+  def store(id: PathId, value: TaskFailure): Future[TaskFailure] =
+    super.storeWithoutVersion(id.safePath, value)
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/state/TaskFailureRepository.scala]: Just curious: why super?

File: src/main/scala/mesosphere/marathon/state/EntityRepository.scala [hunk 5]
```diff
@@ -84,9 +84,13 @@ trait EntityRepository[T <: MarathonState[_, T]] extends StateMetrics {
 
   protected def storeWithVersion(id: String, version: Timestamp, t: T): Future[T] = {
     for {
-      alias <- this.store.store(id, t)
-      result <- this.store.store(id + ID_DELIMITER + version, t)
+      alias <- storeWithoutVersion(id, t)
+      result <- storeWithoutVersion(id + ID_DELIMITER + version, t)
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/state/EntityRepository.scala]: You use the method storeWithoutVersion to store a version here...
