### PR TITLE
Fix Residency behavior with Instances

### LINKED ISSUE #4429: Fix resident tasks

### PR DESCRIPTION
**Pull request by meichstedt**
**Note** I'm still fixing some integration tests; will add more commits.

Generate events that shall get published in the InstanceOpProcessor
    
* Events will be generated where we know what exactly should be reported
* If a status update is the trigger for an instance change, the status update state will be reported
* Resident instances that return to Reserved after they terminate will be reported with the original terminal state
    
Resolves #4429

### CODE REVIEW

File: src/main/scala/mesosphere/marathon/core/instance/Instance.scala [hunk 1]
```diff
@@ -46,57 +48,78 @@ case class Instance(
...
+            case TaskUpdateEffect.Noop =>
+              InstanceUpdateEffect.Noop(instance.instanceId)
+
+            case TaskUpdateEffect.Failure(cause) =>
+              InstanceUpdateEffect.Failure(cause)
+
+            case _ =>
+              InstanceUpdateEffect.Failure("ForceExpunge should never delegated to an instance")
+          }
+        }.getOrElse(InstanceUpdateEffect.Failure(s"$taskId not found in $instanceId"))
```
Comment (jasongilanfarr) [inline src/main/scala/mesosphere/marathon/core/instance/Instance.scala]: Should there be a not found that extends failed?

Comment (jasongilanfarr) [inline src/main/scala/mesosphere/marathon/core/instance/Instance.scala]: Maybe for the other cases too?

File: src/main/scala/mesosphere/marathon/core/instance/update/InstanceChangedEventsGenerator.scala [hunk 2]
```diff
@@ -0,0 +1,45 @@
+package mesosphere.marathon.core.instance.update
+
+import mesosphere.marathon.core.event.{ InstanceChanged, MarathonEvent, MesosStatusUpdateEvent }
+import mesosphere.marathon.core.instance.{ Instance, InstanceStatus }
+import mesosphere.marathon.core.task.Task
+import mesosphere.marathon.state.Timestamp
+
+import scala.collection.immutable.Seq
+
+class InstanceChangedEventsGenerator {
```
Comment (jasongilanfarr) [inline src/main/scala/mesosphere/marathon/core/instance/update/InstanceChangedEventsGenerator.scala]: Could be an object.

File: src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceOpProcessorImpl.scala [hunk 3]
```diff
@@ -98,7 +105,8 @@ private[tracker] class InstanceOpProcessorImpl(
         // Used for task termination or as a result from a UpdateStatus action.
         // The expunge is propagated to the instanceTracker which informs the sender about the success (see Ack).
         repository.delete(change.instance.instanceId).map { _ => InstanceTrackerActor.Ack(op.sender, change) }
-          .recoverWith(tryToRecover(op)(expectedState = None, oldState = Some(change.instance)))
```
Comment (jasongilanfarr) [inline src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceOpProcessorImpl.scala]: This and others here could benefit from async/await

File: src/main/scala/mesosphere/marathon/core/task/update/TaskUpdateOperation.scala [hunk 4]
```diff
@@ -1,11 +1,20 @@
...
+import scala.collection.immutable.Seq
+
 /** Trait for operations attempting to change the state of a task */
 trait TaskUpdateOperation extends Product with Serializable
 
 object TaskUpdateOperation {
   case class MesosUpdate(status: InstanceStatus, taskStatus: mesos.Protos.TaskStatus) extends TaskUpdateOperation
+
+  case class LaunchOnReservation(
+    runSpecVersion: Timestamp,
```
Comment (jasongilanfarr) [inline src/main/scala/mesosphere/marathon/core/task/update/TaskUpdateOperation.scala]: Doesn't have the runSpec? Seems like that'd be handy.

Comment (jasongilanfarr) [inline src/main/scala/mesosphere/marathon/core/task/update/TaskUpdateOperation.scala]: Even if it's just the id.

**Comment by aquamatthias** [comment]
retest this please

**Comment by aquamatthias** [comment]
retest this please

File: src/main/scala/mesosphere/marathon/core/instance/Instance.scala [hunk 5]
```diff
@@ -45,58 +49,79 @@ case class Instance(
...
-      case InstanceUpdateOperation.LaunchOnReservation(_, version, status, hostPorts) =>
+        tasks.find(_.taskId == taskId).map { task =>
+          val taskEffect = task.update(TaskUpdateOperation.MesosUpdate(status, mesosStatus, now))
+          taskEffect match {
+            case TaskUpdateEffect.Update(newTaskState) =>
+              val updated: Instance = updatedInstance(newTaskState, now)
+              val events = eventsGenerator.events(status, updated, Some(task), now)
+              updated.state.status match {
+                case t: Terminal =>
+                  InstanceUpdateEffect.Expunge(updated, events)
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/instance/Instance.scala]: We probably should expunge in the case of all tasks are terminal.
The instance can go to a terminal state in those cases:
```
    Error,
    Failed,
    Gone,
    Dropped
```
But not all tasks need to be in a terminal state.

File: src/main/scala/mesosphere/marathon/core/instance/Instance.scala [hunk 6]
```diff
@@ -203,14 +229,20 @@ object Instance {
...
+    def defaultVersion: Timestamp = {
+      // TODO(PODS): fix this
+      log.error("A default Timestamp.zero breaks things!")
+      Timestamp.zero
+    }
+    new Instance(task.taskId.instanceId, task.agentInfo,
+      InstanceState(
+        status = task.status.taskStatus,
+        since = task.status.startedAt.getOrElse(task.status.stagedAt),
+        version = task.version.getOrElse(defaultVersion),
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/instance/Instance.scala]: Can we see tasks without version?

File: src/main/scala/mesosphere/marathon/core/instance/update/InstanceChangedEventsGenerator.scala [hunk 7]
```diff
@@ -0,0 +1,45 @@
...
+        status.toMesosStateName,
+        message,
+        appId = runSpecId,
+        host,
+        ipAddresses,
+        ports = ports,
+        version = version.toString,
+        timestamp = now.toString
+      )
+      Seq[MarathonEvent](instanceEvent, taskEvent)
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/instance/update/InstanceChangedEventsGenerator.scala]: Nit: perhaps change the order, so that subscribers see the MesosStatusUpdate first and the InstanceChange afterwards?

File: src/main/scala/mesosphere/marathon/core/task/Task.scala [hunk 8]
```diff
@@ -311,21 +310,22 @@ object Task {
...
         ))
         TaskUpdateEffect.Update(newState = updatedTask)
 
-      case TaskUpdateOperation.MesosUpdate(newStatus, mesosStatus) =>
+      // The Terminal extractor applies specific logic e.g. when an Unreachable task becomes Gone
+      case TaskUpdateOperation.MesosUpdate(newStatus: Terminal, mesosStatus, _) =>
+        val updated = copy(status = status.copy(
+          mesosStatus = Some(mesosStatus),
+          taskStatus = newStatus))
+        TaskUpdateEffect.Update(updated)
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/task/Task.scala]: The effect was expunge before the change. I guess we will update always on the level on tasks and expunge on the level of instances? (do we need TaskUpdateEffect.Expunge?)

File: src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceOpProcessorImpl.scala [hunk 9]
```diff
@@ -69,7 +75,8 @@ private[tracker] object InstanceOpProcessorImpl {
     private[this] def expungeInstance(id: Instance.Id)(implicit ec: ExecutionContext): Future[InstanceUpdateEffect] = {
       directInstanceTracker.instance(id).map {
         case Some(existingInstance: Instance) =>
-          InstanceUpdateEffect.Expunge(existingInstance)
+          val events = eventsGenerator.events(InstanceStatus.Killed, existingInstance, task = None, clock.now())
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceOpProcessorImpl.scala]: Q: why can we say Killed here?

File: src/main/scala/mesosphere/marathon/core/task/Task.scala (hunk 8 above)
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/task/Task.scala]: Should have read to the end. I see you deleted it already. Thanks!

File: src/main/scala/mesosphere/marathon/core/instance/Instance.scala (hunk 6 above)
Comment (meichstedt) [inline src/main/scala/mesosphere/marathon/core/instance/Instance.scala]: Yes, Task.Reserved does currently not have a version unfortunately. An instance will always have one though.

File: src/main/scala/mesosphere/marathon/core/task/Task.scala (hunk 8 above)
Comment (meichstedt) [inline src/main/scala/mesosphere/marathon/core/task/Task.scala]: Exactly 😎

File: src/main/scala/mesosphere/marathon/core/instance/update/InstanceChangedEventsGenerator.scala (hunk 7 above)
Comment (meichstedt) [inline src/main/scala/mesosphere/marathon/core/instance/update/InstanceChangedEventsGenerator.scala]: Makes sense to me, will do in another PR. might break some tests that verify the order though, so I'd do this with lower prio.

File: src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceOpProcessorImpl.scala (hunk 9 above)
Comment (meichstedt) [inline src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceOpProcessorImpl.scala]: A: Actually we can't. I didn't want to introduce a new state but obviously forgot the `TODO`. Background is that we need to publish an event here that notifies subscribers of _this instance is terminal_. When we forcefully expunge a `Running` task, `Running` is not sufficient for that. Thought about `Deleted`, but I need to further think about that. Thoughts on this?

Comment (jdef) [inline src/main/scala/mesosphere/marathon/core/task/tracker/impl/InstanceOpProcessorImpl.scala]: What about Terminating (read: this is a termination in progress). Killing might be an instance of Terminating. Suicidal might be an instance of Terminating (meaning we're expecting that Mesos will kill any remaining tasks)
