### PR TITLE
Fixes #3723 - Fix validation of duplicate volume names

### LINKED ISSUE #3723: external volumes: allows user to create multiple zero-instance apps that ref the same volume, and then scale them both to 1
* It also lets me create an app (instances = 1) that points to the same ext vol while another, running app is already referencing that external volume.

the group-validation isn't working

### PR DESCRIPTION
**Pull request by kolloch**

### CODE REVIEW

File: src/main/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProvider.scala [hunk 1]
```diff
@@ -111,28 +113,45 @@ private[impl] object DVDIProviderValidations extends ExternalVolumeValidations {
...
   override lazy val rootGroup = new Validator[Group] {
     override def apply(g: Group): Result = {
-      val appsByVolume =
+      val appsByVolume: Map[String, Set[PathId]] =
         g.transitiveApps
           .flatMap { app => namesOfMatchingVolumes(app).map(_ -> app.id) }
           .groupBy { case (volumeName, _) => volumeName }
           .mapValues(_.map { case (volumeName, appId) => appId })
 
-      val groupViolations = g.apps.flatMap { app =>
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProvider.scala]: The `g.apps` instead of `g.transitiveApps` prevented validation of apps in nested groups.

File: src/main/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProvider.scala [hunk 2]
```diff
@@ -115,24 +115,39 @@ private[impl] object DVDIProviderValidations extends ExternalVolumeValidations {
...
+
+          isTrue { (vol: ExternalVolume) =>
+            val conflictingAppIds = conflictingApps(vol).mkString(", ")
+            s"Volume name '${vol.external.name}' in $appId conflicts with volume(s) of same name in app(s): " +
+              s"$conflictingAppIds"
+          }{ vol => conflictingApps(vol).isEmpty }
+        }
+
+        validator[AppDefinition] { app =>
+          app.externalVolumes is every(volumeNameUnique(app.id))
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProvider.scala]: To have the correct path here, you can do:
```scala
app.externalVolumes as "container/volumes" is every(volumeNameUnique(app.id))
```

File: src/main/scala/mesosphere/marathon/state/Group.scala [hunk 3]
```diff
@@ -221,24 +231,11 @@ object Group {
...
-        maxApps.filter(group.transitiveApps.size > _).map { num =>
-          Failure(Set(RuleViolation(group,
-            s"""This Marathon instance may only handle up to $num Apps!
-                |(Override with command line option --max_apps)""".stripMargin, None)))
-        } getOrElse Success
-      } and validator(group)
-    }
+    // We do not want a "/value" prefix, therefore we do not create nested validators with validator[Group]
+    // but chain the validators directly.
+    valid(doesNotExceedMaxApps) and
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/state/Group.scala]: do you have to use `valid()` here? Just use `doesNotExceedMaxApps` directly.

File: src/main/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProvider.scala [hunk 4]
```diff
@@ -115,24 +115,39 @@ private[impl] object DVDIProviderValidations extends ExternalVolumeValidations {
...
-            if otherApp != app.id // do not compare to self
-          } yield RuleViolation(app.id, s"Requested volume $name conflicts with a volume in app $otherApp", None)
+      val appValid: Validator[AppDefinition] = {
+        def volumeNameUnique(appId: PathId): Validator[ExternalVolume] = {
+          def conflictingApps(vol: ExternalVolume): Set[PathId] =
+            appsByVolume.getOrElse(vol.external.name, Set.empty).filter(_ != appId)
+
+          isTrue { (vol: ExternalVolume) =>
+            val conflictingAppIds = conflictingApps(vol).mkString(", ")
+            s"Volume name '${vol.external.name}' in $appId conflicts with volume(s) of same name in app(s): " +
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProvider.scala]: Let's fix the path, and make the description simple. 
The `conflictingApps` function can be moved inside the isTrue block.

**Comment by aquamatthias** [comment]
@kolloch added some suggestions but generally looks good.

File: src/main/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProvider.scala (hunk 2 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProvider.scala]: Then the index is wrong

Matthias Veit <notifications@github.com> schrieb am Di., 12. Apr. 2016
08:12:

File: src/main/scala/mesosphere/marathon/state/Group.scala (hunk 3 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/state/Group.scala]: Ack

File: src/main/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProvider.scala (hunk 4 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProvider.scala]: I am not sure what is best there. I'll keep it "as is". We can improve it later.

**Comment by aquamatthias** [comment]
Thanks!

File: src/test/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProviderRootGroupValidationTest.scala [hunk 5]
```diff
@@ -0,0 +1,133 @@
...
+        RuleViolation(
+          value = app2.externalVolumes.head,
+          constraint = "Volume name 'vol' in /nested/app2 conflicts with volume(s) of same name in app(s): /nested/app1",
+          description = Some("/groups(0)/apps(1)/externalVolumes(0)")
+        )
+      )
+    )
+  }
+
+  class Fixture {
```
Comment (jdef) [inline src/test/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProviderRootGroupValidationTest.scala]: why is this a class instead of an object?

File: src/test/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProviderRootGroupValidationTest.scala [hunk 6]
```diff
@@ -0,0 +1,133 @@
...
+    val rootGroup = Group(
+      id = PathId.empty,
+      groups = Set(
+        Group(
+          id = PathId("/nested"),
+          apps = Set(app1, app2)
+        )
+      )
+    )
+
```
Comment (jdef) [inline src/test/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProviderRootGroupValidationTest.scala]: TODO: `test("two volumes with same name, one in an app where instances=0, should succeed")`

Comment (jdef) [inline src/test/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProviderRootGroupValidationTest.scala]: fixed by #3751

File: src/test/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProviderRootGroupValidationTest.scala (hunk 5 above)
Comment (kolloch) [inline src/test/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProviderRootGroupValidationTest.scala]: We use a similar pattern elsewhere. If your `Fixture` contains state, it is nice to use a new instance for every test run.
