### PR TITLE
Fixes #2405 0.13 migration failure

### LINKED ISSUE #2405: Migration of ZK State to 0.13/0.14 does not work
Started some tasks in 0.11 and restarted on master. Got following stack trace:

marathon [2015-10-12 16:19:56,348] ERROR Migration failed! (mesosphere.marathon.state.Migration:97)
marathon java.lang.RuntimeException: while migrating storage to 0.13
marathon 	at mesosphere.marathon.state.Migration$$anonfun$migrations$4$$anonfun$apply$2.applyOrElse(Migration.scala:62)
marathon 	at mesosphere.marathon.state.Migration$$anonfun$migrations$4$$anonfun$apply$2.applyOrElse(Migration.scala:61)
marathon 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
marathon 	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
marathon 	at scala.util.Try$.apply(Try.scala:192)
marathon 	at scala.util.Failure.recover(Try.scala:216)
marathon 	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324)
marathon 	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324)
marathon 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
marathon 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
marathon 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
marathon 	at java.lang.Thread.run(Thread.java:745)
marathon Caused by: mesosphere.marathon.StoreCommandFailedException: Could not fetch MarathonTaskState with key: app:app.8f61d32e-70e6-11e5-a216-7a090c3edc79
marathon 	at mesosphere.marathon.state.MarathonStore$$anonfun$mesosphere$marathon$state$MarathonStore$$exceptionTransform$1.applyOrElse(MarathonStore.scala:75)
marathon 	at mesosphere.marathon.state.MarathonStore$$anonfun$mesosphere$marathon$state$MarathonStore$$exceptionTransform$1.applyOrElse(MarathonStore.scala:74)
marathon 	... 10 more
marathon Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
marathon 	at com.google.protobuf.InvalidProtocolBufferException.invalidEndTag(InvalidProtocolBufferException.java:94)
marathon 	at com.google.protobuf.CodedInputStream.checkLastTagWas(CodedInputStream.java:124)
marathon 	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:143)
marathon 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:176)
marathon 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:188)
marathon 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:193)
marathon 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
marathon 	at mesosphere.marathon.Protos$MarathonTask.parseFrom(Protos.java:8377)
marathon 	at mesosphere.marathon.state.MarathonTaskState.mergeFromProto(MarathonTaskState.scala:15)
marathon 	at mesosphere.marathon.state.MarathonTaskState.mergeFromProto(MarathonTaskState.scala:9)
marathon 	at mesosphere.marathon.state.MarathonStore.mesosphere$marathon$state$MarathonStore$$stateFromBytes(MarathonStore.scala:79)
marathon 	at mesosphere.marathon.state.MarathonStore$$anonfun$fetch$1$$anonfun$apply$2.apply(MarathonStore.scala:35)
marathon 	at mesosphere.marathon.state.MarathonStore$$anonfun$fetch$1$$anonfun$apply$2.apply(MarathonStore.scala:33)
marathon 	at scala.Option.map(Option.scala:146)
marathon 	at mesosphere.marathon.state.MarathonStore$$anonfun$fetch$1.apply(MarathonStore.scala:33)
marathon 	at mesosphere.marathon.state.MarathonStore$$anonfun$fetch$1.apply(MarathonStore.scala:33)
marathon 	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
marathon 	at scala.util.Try$.apply(Try.scala:192)
marathon 	at scala.util.Success.map(Try.scala:237)
marathon 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
marathon 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
marathon 	... 4 more

### PR DESCRIPTION
**Pull request by meichstedt**
Serialized MarathonTask entities are now deserialized using the old format.

### CODE REVIEW

**Comment by aquamatthias** [comment]
This is a breaking change. Can you please add a note to the changelog? Thanks!

File: src/test/scala/mesosphere/marathon/state/MigrationTo0_13Test.scala [hunk 1]
```diff
@@ -44,8 +43,9 @@ class MigrationTo0_13Test extends MarathonSpec with GivenWhenThen with Matchers
 
   class Fixture {
     lazy val uuidGenerator = Generators.timeBasedGenerator(EthernetAddress.fromInterface())
-    lazy val state = spy(new InMemoryStore)
+    lazy val state = new InMemoryStore
     lazy val metrics = new Metrics(new MetricRegistry)
+    lazy val legacyTaskStore = new LegacyTaskStore(state)
```
Comment (aquamatthias) [inline src/test/scala/mesosphere/marathon/state/MigrationTo0_13Test.scala]: Cool that you added that test case!

**Comment by aquamatthias** [comment]
Tested that with tasks created with 0.11. Migration worked. :+1: 
If you add the changelog entry, I will merge this.

**Comment by meichstedt** [comment]
Thanks for the review – I added a change log entry, please review that one as well.

**Comment by aquamatthias** [comment]
Thanks!
