### PR TITLE
Fixes #2381 - propagate task updates in defined order

### LINKED ISSUE #2381: Marathon stops apps instead of restart
I've got another issue in addition to #2360. This is how the group looks like after deployment to `PUT /v2/groups`:

image

Hierarchy looks like this:

* `/app/db` — 3 apps in this group, `minimumHealthCapacity` is 0
* `/app/engine` — 6 apps in this group, `minimumHealthCapacity` is 0
* `/app/svc` — 2 apps in this group, `minimumHealthCapacity` is 1

Let's take a look at one engine.

Timeline:

1. `11:03:11.108` app is running.
2. `11:05:04.767` deploy triggered, single instance killed and DEPLOY STOPPED.
3. `11:08:11.154` app started again.

Here are the logs for one app:

```
October 8th 2015, 11:08:35.487	[INFO] [10/08/2015 10:08:11.543] [marathon-akka.actor.default-dispatcher-23] [akka://marathon/user/launchQueue/2/9-app_engine_execution] No tasks left to launch. Stop receiving offers for /app/engine/execution, 2015-10-08T10:05:04.724Z
October 8th 2015, 11:08:34.378	[2015-10-08 10:08:11,542] INFO Offer [20150930-060945-269165578-5050-12932-O444787]. Insufficient resources for [/app/engine/execution] (need cpus=0.1, mem=1024.0, disk=0.0, ports=(), available in offer:
October 8th 2015, 11:08:33.286	[2015-10-08 10:08:11,541] INFO Offer [20150930-060945-269165578-5050-12932-O444786]. Insufficient resources for [/app/engine/execution] (need cpus=0.1, mem=1024.0, disk=0.0, ports=(), available in offer:
October 8th 2015, 11:08:32.355	[2015-10-08 10:08:11,491] INFO Offer [20150930-060945-269165578-5050-12932-O444785]. Insufficient resources for [/app/engine/execution] (need cpus=0.1, mem=1024.0, disk=0.0, ports=(), available in offer:
October 8th 2015, 11:08:31.118	[2015-10-08 10:08:11,490] INFO Offer [20150930-060945-269165578-5050-12932-O444784]. Insufficient resources for [/app/engine/execution] (need cpus=0.1, mem=1024.0, disk=0.0, ports=(), available in offer:
October 8th 2015, 11:08:30.009	[2015-10-08 10:08:11,489] INFO Offer [20150930-060945-269165578-5050-12932-O444783]. Insufficient resources for [/app/engine/execution] (need cpus=0.1, mem=1024.0, disk=0.0, ports=(), available in offer:
October 8th 2015, 11:08:28.690	[2015-10-08 10:08:11,448] INFO Offer [20150930-060945-269165578-5050-12932-O444782]. Insufficient resources for [/app/engine/execution] (need cpus=0.1, mem=1024.0, disk=0.0, ports=(), available in offer:
October 8th 2015, 11:08:27.023	[2015-10-08 10:08:11,446] INFO Offer [20150930-060945-269165578-5050-12932-O444781]. Insufficient resources for [/app/engine/execution] (need cpus=0.1, mem=1024.0, disk=0.0, ports=(), available in offer:
October 8th 2015, 11:08:25.298	[2015-10-08 10:08:11,445] INFO Offer [20150930-060945-269165578-5050-12932-O444780]. Insufficient resources for [/app/engine/execution] (need cpus=0.1, mem=1024.0, disk=0.0, ports=(), available in offer:
October 8th 2015, 11:08:22.980	[2015-10-08 10:08:11,444] INFO Offer [20150930-060945-269165578-5050-12932-O444779]. Insufficient resources for [/app/engine/execution] (need cpus=0.1, mem=1024.0, disk=0.0, ports=(), available in offer:
October 8th 2015, 11:08:21.309	[2015-10-08 10:08:11,442] INFO Offer [20150930-060945-269165578-5050-12932-O444778]. Insufficient resources for [/app/engine/execution] (need cpus=0.1, mem=1024.0, disk=0.0, ports=(), available in offer:
October 8th 2015, 11:08:17.243	[2015-10-08 10:08:11,409] INFO Offer [20150930-060945-269165578-5050-12932-O444777]. Insufficient resources for [/app/engine/execution] (need cpus=0.1, mem=1024.0, disk=0.0, ports=(), available in offer:
October 8th 2015, 11:08:15.654	[2015-10-08 10:08:11,407] INFO Offer [20150930-060945-269165578-5050-12932-O444776]. Insufficient resources for [/app/engine/execution] (need cpus=0.1, mem=1024.0, disk=0.0, ports=(), available in offer:
October 8th 2015, 11:08:15.282	[2015-10-08 10:08:11,407] INFO Offer [20150930-060945-269165578-5050-12932-O444775]. Insufficient resources for [/app/engine/execution] (need cpus=0.1, mem=1024.0, disk=0.0, ports=(), available in offer:
October 8th 2015, 11:08:13.957	[2015-10-08 10:08:11,406] INFO Offer [20150930-060945-269165578-5050-12932-O444774]. Insufficient resources for [/app/engine/execution] (need cpus=0.1, mem=1024.0, disk=0.0, ports=(), available in offer:
October 8th 2015, 11:08:13.030	[2015-10-08 10:08:11,405] INFO Offer [20150930-060945-269165578-5050-12932-O444773]. Insufficient resources for [/app/engine/execution] (need cpus=0.1, mem=1024.0, disk=0.0, ports=(), available in offer:
October 8th 2015, 11:08:11.973	[2015-10-08 10:08:11,405] INFO Offer [20150930-060945-269165578-5050-12932-O444772]. Insufficient resources for [/app/engine/execution] (need cpus=0.1, mem=1024.0, disk=0.0, ports=(), available in offer:
October 8th 2015, 11:08:11.154	[2015-10-08 10:08:11,108] INFO Queueing 1 new tasks for /app/engine/execution (0 queued or running) (mesosphere.marathon.SchedulerActions:520)
October 8th 2015, 11:08:11.107	[2015-10-08 10:08:11,105] INFO Need to scale /app/engine/execution from 0 up to 1 instances (mesosphere.marathon.SchedulerActions:514)
October 8th 2015, 11:05:17.835	[2015-10-08 10:05:11,247] INFO Increasing delay. Task launch delay for [/app/engine/execution] changed from [0 milliseconds] to [1 seconds]. (mesosphere.marathon.core.launchqueue.impl.RateLimiter$:52)
October 8th 2015, 11:05:17.701	[INFO] [10/08/2015 10:05:09.264] [marathon-akka.actor.default-dispatcher-30] [akka://marathon/user/MarathonScheduler/$a/DeploymentManager/8ee9acf7-c784-46d9-9efd-a68997a3d16b/$f] All tasks for /app/engine/execution are healthy
October 8th 2015, 11:05:17.607	[INFO] [10/08/2015 10:05:07.151] [marathon-akka.actor.default-dispatcher-54] [akka://marathon/user/launchQueue/2/9-app_engine_execution] No tasks left to launch. Stop receiving offers for /app/engine/execution, 2015-10-08T10:05:04.724Z
October 8th 2015, 11:05:17.509	[INFO] [10/08/2015 10:05:06.167] [marathon-akka.actor.default-dispatcher-43] [akka://marathon/user/MarathonScheduler/$a/DeploymentManager/8ee9acf7-c784-46d9-9efd-a68997a3d16b/$f] Reconciliating tasks during app /app/engine/execution restart: queuing 1 new tasks
October 8th 2015, 11:05:17.509	[ERROR] [10/08/2015 10:05:06.167] [marathon-akka.actor.default-dispatcher-43] [akka://marathon/user/MarathonScheduler/$a/DeploymentManager/8ee9acf7-c784-46d9-9efd-a68997a3d16b/$f] Old task app_engine_execution.9b6ad4d5-6da1-11e5-9e56-000f532c02a0 failed on slave 20150908-164039-319497226-5050-29034-S5 during app /app/engine/execution restart
October 8th 2015, 11:05:17.509	[INFO] [10/08/2015 10:05:06.167] [marathon-akka.actor.default-dispatcher-52] [akka://marathon/user/launchQueue/2/9-app_engine_execution] scaling change for '/app/engine/execution', version 2015-10-08T10:05:04.724Z with 1 initial tasks
October 8th 2015, 11:05:05.009	[WARN] [10/08/2015 10:05:04.811] [marathon-akka.actor.default-dispatcher-57] [akka://marathon/user/launchQueue/2/9-app_engine_execution] Received delay update for other app: DelayUpdate(AppDefinition(/app/engine/execution,None,None,None,Map(REDACTED -> true),1,0.1,1024.0,0.0,,Set(field: "hostname"
October 8th 2015, 11:05:04.963	[INFO] [10/08/2015 10:05:04.810] [marathon-akka.actor.default-dispatcher-59] [akka://marathon/user/MarathonScheduler/$a/DeploymentManager/8ee9acf7-c784-46d9-9efd-a68997a3d16b/$f] For minimumHealthCapacity 0.0 of /app/engine/execution leave 0 tasks running, maximum capacity 1, killing 1 tasks immediately
October 8th 2015, 11:05:04.921	* Restart(App(/app/engine/execution, image="mydocker.registry/myapp/execution:1.2.3.4.5")))
October 8th 2015, 11:05:04.875	[2015-10-08 10:05:04,757] INFO [/app/engine/execution] storing new app version 2015-10-08T10:05:04.724Z (mesosphere.marathon.state.GroupManager:144)
October 8th 2015, 11:05:04.874	* Restart(App(/app/engine/execution, image="mydocker.registry/myapp/execution:1.2.3.4.5")))
October 8th 2015, 11:05:04.831	* Restart(App(/app/engine/execution, image="mydocker.registry/myapp/execution:1.2.3.4.5")))
October 8th 2015, 11:05:04.767	[2015-10-08 10:05:04,730] INFO [/app/engine/execution]: restart detected for app (oldVersion FullVersionInfo(2015-10-08T09:47:36.555Z,2015-10-08T09:47:36.555Z,2015-09-25T16:02:41.400Z)) (mesosphere.marathon.upgrade.GroupVersioningUtil$:38)
October 8th 2015, 11:03:11.108	[2015-10-08 10:03:11,106] INFO Already running 1 instances of /app/engine/execution. Not scaling. (mesosphere.marathon.SchedulerActions:538)
October 8th 2015, 10:58:11.150	[2015-10-08 09:58:11,106] INFO Already running 1 instances of /app/engine/execution. Not scaling. (mesosphere.marathon.SchedulerActions:538)
October 8th 2015, 10:53:11.138	[2015-10-08 09:53:11,109] INFO Already running 1 instances of /app/engine/execution. Not scaling. (mesosphere.marathon.SchedulerActions:538)
```

Marathon 0.11.0, Mesos 0.23.0. I've seen similar on 0.10.0, but can't be sure.

Tried to replicate locally with no luck.

### PR DESCRIPTION
**Pull request by kolloch**
at least for the things where it matters.

### CODE REVIEW

File: src/main/scala/mesosphere/marathon/core/CoreGuiceModule.scala [hunk 1]
```diff
@@ -45,6 +56,28 @@ class CoreGuiceModule extends AbstractModule {
...
+  def taskStatusUpdateSteps(
+    notifyHealthCheckManagerStepImpl: NotifyHealthCheckManagerStepImpl,
+    acknowledgeTaskUpdateStepImpl: AcknowledgeTaskUpdateStepImpl,
+    notifyRateLimiterStepImpl: NotifyRateLimiterStepImpl,
+    emitUpdateStepImpl: EmitUpdateStepImpl,
+    postTaskStatusEventStepImpl: PostTaskStatusEventStepImpl,
+    scaleAppUpdateStepImpl: ScaleAppUpdateStepImpl,
+    notifyLaunchQueueStepImpl: NotifyLaunchQueueStepImpl,
+    updateTaskTrackerStepImpl: UpdateTaskTrackerStepImpl): Seq[TaskStatusUpdateStep] = {
+    Seq(
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/CoreGuiceModule.scala]: Like that - very readable. Although would like to have 1 or 2 sentences documentation here, why this order is important.

File: src/main/scala/mesosphere/marathon/core/launchqueue/impl/LaunchQueueActor.scala [hunk 2]
```diff
@@ -130,6 +138,18 @@ private[impl] class LaunchQueueActor(
     suspendedLaunchersMessages += actorRef -> deferredMessages
   }
 
+  private[this] def receiveTaskUpdate: Receive = {
+    case update: TaskStatusUpdate =>
+      import context.dispatcher
+      launchers.get(update.appId) match {
+        case Some(actorRef) =>
+          val eventualCount: Future[QueuedTaskCount] =
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/launchqueue/impl/LaunchQueueActor.scala]: why the name eventualCount?

File: src/main/scala/mesosphere/marathon/core/launchqueue/impl/LaunchQueueDelegate.scala [hunk 3]
```diff
@@ -33,13 +37,18 @@ private[launchqueue] class LaunchQueueDelegate(
   override def add(app: AppDefinition, count: Int): Unit = askQueueActor("add")(LaunchQueueDelegate.Add(app, count))
 
   private[this] def askQueueActor[T](method: String)(message: T): Any = {
+    val answerFuture: Future[Any] = askQueueActorFuture(method)(message)
+    Await.result(answerFuture, config.launchQueueRequestTimeout().milliseconds)
+  }
+
+  def askQueueActorFuture[T](method: String)(message: T): Future[Any] = {
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/launchqueue/impl/LaunchQueueDelegate.scala]: message should be error message?

Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/launchqueue/impl/LaunchQueueDelegate.scala]: can the scope also be private[this] (according to the code it can) or is there any reason for that?

File: src/main/scala/mesosphere/marathon/core/launchqueue/impl/LaunchQueueDelegate.scala [hunk 4]
```diff
@@ -33,13 +37,18 @@ private[launchqueue] class LaunchQueueDelegate(
...
     implicit val timeout: Timeout = 1.second
     val answerFuture = actorRef ? message
     import scala.concurrent.ExecutionContext.Implicits.global
     answerFuture.recover {
-      case NonFatal(e) => throw new RuntimeException(s"in $method", e)
+      case NonFatal(e) => throw new scala.RuntimeException(s"in $method", e)
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/launchqueue/impl/LaunchQueueDelegate.scala]: why scala.RuntimeException?

File: src/main/scala/mesosphere/marathon/core/task/tracker/TaskStatusUpdateProcessor.scala [hunk 5]
```diff
@@ -1,9 +1,9 @@
 package mesosphere.marathon.core.task.tracker
 
-import mesosphere.marathon.core.task.bus.TaskStatusObservables
+import org.apache.mesos.Protos.TaskStatus
 
 import scala.concurrent.Future
 
 trait TaskStatusUpdateProcessor {
-  def publish(status: TaskStatusObservables.TaskStatusUpdate): Future[Unit]
+  def publish(status: TaskStatus): Future[Unit]
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/task/tracker/TaskStatusUpdateProcessor.scala]: Did you think about using the scala case class mesosphere.mesos.protos.TaskStatus instead of the pure proto generated one? Do you see value in that?

File: src/main/scala/mesosphere/marathon/core/task/tracker/impl/ContinueOnErrorStep.scala [hunk 6]
```diff
@@ -0,0 +1,35 @@
+package mesosphere.marathon.core.task.tracker.impl
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/task/tracker/impl/ContinueOnErrorStep.scala]: Just for clearness: move all step implementations in one package?

File: src/main/scala/mesosphere/marathon/core/task/tracker/impl/EmitUpdateStepImpl.scala [hunk 7]
```diff
@@ -0,0 +1,28 @@
+package mesosphere.marathon.core.task.tracker.impl
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/task/tracker/impl/EmitUpdateStepImpl.scala]: Just for clearness: move the implementation steps into separate package?

File: src/main/scala/mesosphere/marathon/core/task/tracker/impl/EmitUpdateStepImpl.scala [hunk 8]
```diff
@@ -0,0 +1,28 @@
...
+import mesosphere.marathon.core.task.tracker.TaskStatusUpdateStep
+import mesosphere.marathon.state.{ AppDefinition, PathId, Timestamp }
+import org.apache.mesos.Protos.TaskStatus
+
+import scala.concurrent.Future
+
+/**
+  * Forward the update to the taskStatusEmitter.
+  */
+class EmitUpdateStepImpl @Inject() (taskStatusEmitter: TaskStatusEmitter) extends TaskStatusUpdateStep {
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/task/tracker/impl/EmitUpdateStepImpl.scala]: In the chain of task status updates, the name `EmitUpdate` really is not very informative.

File: src/main/scala/mesosphere/marathon/core/task/tracker/impl/PostTaskStatusEventStepImpl.scala [hunk 9]
```diff
@@ -0,0 +1,77 @@
...
+}
+import org.apache.mesos.Protos.TaskStatus
+import org.slf4j.LoggerFactory
+
+import scala.concurrent.Future
+
+/**
+  * Post this update to the internal event stream.
+  */
+class PostTaskStatusEventStepImpl @Inject() (
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/task/tracker/impl/PostTaskStatusEventStepImpl.scala]: Suggestion: `PostToEventStreamStep` ?

File: src/main/scala/mesosphere/marathon/core/task/tracker/impl/TaskStatusUpdateProcessorImpl.scala [hunk 10]
```diff
@@ -1,133 +1,85 @@
...
-          // In production, it should not matter if we do not delay some task launches so much.
-          appOption.foreach(launchQueue.addDelay)
+  private[this] def processUpdate(
+    timestamp: Timestamp,
+    appId: PathId,
+    maybeApp: Option[AppDefinition],
+    maybeTask: Option[MarathonTask],
+    mesosStatus: TaskStatus): Future[Unit] = {
+    steps.foldLeft(Future.successful(())) { (resultSoFar, nextStep) =>
+      stepTimers(nextStep.name).timeFuture {
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/task/tracker/impl/TaskStatusUpdateProcessorImpl.scala]: [Not for this PR] can we rename timeFuture into apply and handle it the same way as the non future based version?

File: src/main/scala/mesosphere/marathon/core/task/tracker/impl/TaskStatusUpdateProcessorImpl.scala [hunk 11]
```diff
@@ -1,133 +1,85 @@
...
   private[this] val log = LoggerFactory.getLogger(getClass)
 
-  //TODO: fix style issue and enable this scalastyle check
-  //scalastyle:off cyclomatic.complexity method.length
-  def publish(incoming: TaskStatusObservables.TaskStatusUpdate): Future[Unit] = incoming match {
-    case TaskStatusUpdate(timestamp, taskId, WithMesosStatus(status)) =>
-      val appId = taskIdUtil.appId(taskId)
+  private[this] val publishFutureTimer: Timer =
+    metrics.timer(metrics.name(MetricPrefixes.SERVICE, getClass, "publishFuture"))
+  private[this] val fetchTaskTimer: Timer = metrics.timer(metrics.name(MetricPrefixes.SERVICE, getClass, "fetchTask"))
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/task/tracker/impl/TaskStatusUpdateProcessorImpl.scala]: fetchTask: that metric should be provided from the caller side not the callee side?
(Otherwise all users of fetchTask need to have that metric)

File: src/main/scala/mesosphere/marathon/core/task/tracker/impl/TaskStatusUpdateProcessorImpl.scala [hunk 12]
```diff
@@ -1,133 +1,85 @@
...
+  private[this] val getAppTimer: Timer = metrics.timer(metrics.name(MetricPrefixes.SERVICE, getClass, "getApp"))
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/task/tracker/impl/TaskStatusUpdateProcessorImpl.scala]: appTimer: that metric should be provided from the caller side not the callee side?
(Otherwise all users of fetchTask need to have that metric)

File: src/main/scala/mesosphere/marathon/core/task/tracker/impl/TaskStatusUpdateProcessorImpl.scala [hunk 13]
```diff
@@ -1,133 +1,85 @@
...
-              case NonFatal(t) =>
-                log.warn(s"Task could not be saved. Do not post event for '${taskId.getValue}'", t)
-                driverOpt.foreach(_.killTask(status.getTaskId))
-            }
-
-        case TASK_STAGING if !taskTracker.contains(appId) =>
-          log.warn(s"Received status update for unknown app $appId, killing task ${status.getTaskId}")
-          driverOpt.foreach(_.killTask(status.getTaskId))
-          Future.successful(())
+    val eventuallyMaybeApp = maybeTask match {
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/core/task/tracker/impl/TaskStatusUpdateProcessorImpl.scala]: Is the app definition always used inside the steps?

**Comment by aquamatthias** [comment]
Test coverage decreased noticeable - any plans on improving that?

File: src/main/scala/mesosphere/marathon/core/launchqueue/impl/LaunchQueueActor.scala (hunk 2 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/core/launchqueue/impl/LaunchQueueActor.scala]: It is something that intellij suggests for futures. I can change it if you dislike it.

File: src/main/scala/mesosphere/marathon/core/launchqueue/impl/LaunchQueueDelegate.scala (hunk 3 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/core/launchqueue/impl/LaunchQueueDelegate.scala]: message is the message send to the actor.

yes, this should be `private[this]`.

File: src/main/scala/mesosphere/marathon/core/launchqueue/impl/LaunchQueueDelegate.scala (hunk 4 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/core/launchqueue/impl/LaunchQueueDelegate.scala]: no reason, I'll revert it.

File: src/main/scala/mesosphere/marathon/core/CoreGuiceModule.scala (hunk 1 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/core/CoreGuiceModule.scala]: sure

File: src/main/scala/mesosphere/marathon/core/launchqueue/impl/LaunchQueueActor.scala (hunk 2 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/core/launchqueue/impl/LaunchQueueActor.scala]: I wanted to change it for you but the same convention is used elsewhere in this class. So I leave it for now.

File: src/main/scala/mesosphere/marathon/core/task/tracker/impl/EmitUpdateStepImpl.scala (hunk 7 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/core/task/tracker/impl/EmitUpdateStepImpl.scala]: I like it. I chose `impl.steps`.

File: src/main/scala/mesosphere/marathon/core/task/tracker/impl/TaskStatusUpdateProcessorImpl.scala (hunk 11 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/core/task/tracker/impl/TaskStatusUpdateProcessorImpl.scala]: I wanted to provide a metric from the caller perspective. How much time does it need in the task status update? It might be different from other call sites because of caching, flow, etc.

I can remove it, if you want.

File: src/main/scala/mesosphere/marathon/core/task/tracker/impl/TaskStatusUpdateProcessorImpl.scala (hunk 12 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/core/task/tracker/impl/TaskStatusUpdateProcessorImpl.scala]: same reasoning as above. I like it but I do not insist on it.

File: src/main/scala/mesosphere/marathon/core/task/tracker/impl/PostTaskStatusEventStepImpl.scala (hunk 9 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/core/task/tracker/impl/PostTaskStatusEventStepImpl.scala]: jupp

File: src/main/scala/mesosphere/marathon/core/task/tracker/impl/TaskStatusUpdateProcessorImpl.scala (hunk 13 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/core/task/tracker/impl/TaskStatusUpdateProcessorImpl.scala]: You are right. It is only used in `NotifyRateLimiterStepImpl` if a task has finished but not killed.

good catch!

**Comment by aquamatthias** [comment]
Looks good - Thanks!
Next Steps: 
- please create a ticket for the tests
- please squash the PR
and I will merge. After that cherry pick that change on Master.
