### PR TITLE
Fixes #3423 | Report kills due to failed healthcheck.

### LINKED ISSUE #3423: Report kills due to failed health check in "Last Task Failure"
Currently (v0.15.3) Marathon can kill task due to failed health check, but it doesn't show up in "Last Task Failure" in debug tab. I propose reporting kills as task failures and showing them in debug tab.

### PR DESCRIPTION
**Pull request by janisz**
Health check kills are published as an event and stored as task failure.
They appear in UI showing cause of last failed health check and host
just as normal Mesos task failures.

screenshot from 2016-03-16 16 05 55

### CODE REVIEW

File: src/main/scala/mesosphere/marathon/state/TaskFailure.scala [hunk 1]
```diff
@@ -65,6 +66,26 @@ object TaskFailure {
       slaveId = if (proto.hasSlaveId) Some(proto.getSlaveId) else None
     )
 
+  object FromUnhealthyTaskKillEvent {
+    def unapply(event: UnhealthyTaskKillEvent): Option[TaskFailure] =
+      apply(event)
+
+    def apply(event: UnhealthyTaskKillEvent): Option[TaskFailure] = {
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/state/TaskFailure.scala]: I guess you use the same method signature as `FromMesosStatusUpdateEvent`.
Since there can be different status update this makes sense there, but we want to treat every kill event as task failure. 
Please remove the option from the apply method.

File: src/main/scala/mesosphere/marathon/state/TaskFailure.scala [hunk 2]
```diff
@@ -65,6 +66,26 @@ object TaskFailure {
...
+      val UnhealthyTaskKillEvent(appId, taskId, version, health, host, slaveID, _, _) = event
+
+      Some(TaskFailure(
+        appId,
+        taskId.mesosTaskId,
+        mesos.TaskState.TASK_KILLED,
+        health.lastFailureCause.getOrElse(""),
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/state/TaskFailure.scala]: Perhaps we should always prepend something like:
`"Task was killed since health check failed. Reason: $reason"`
Also: if the failureCause is unset: `getOrElse("unknown")` would be better than an empty string.

File: src/main/scala/mesosphere/marathon/health/HealthCheckActor.scala [hunk 3]
```diff
@@ -3,7 +3,7 @@ package mesosphere.marathon.health
 import akka.actor.{ Actor, ActorLogging, ActorRef, Cancellable, Props }
 import akka.event.EventStream
 import mesosphere.marathon.Protos.HealthCheckDefinition.Protocol
-import mesosphere.marathon.core.task.Task
+import mesosphere.marathon.core.task.{ Task }
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/health/HealthCheckActor.scala]: Remove Parentheses.

File: src/main/scala/mesosphere/marathon/event/Events.scala [hunk 4]
```diff
@@ -206,6 +207,16 @@ case class AppTerminatedEvent(
   eventType: String = "app_terminated_event",
   timestamp: String = Timestamp.now().toString) extends MarathonEvent
 
+case class UnhealthyTaskKillEvent(
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/event/Events.scala]: Please define this event in the health check section.

File: src/main/scala/mesosphere/marathon/event/Events.scala [hunk 5]
```diff
@@ -206,6 +207,16 @@ case class AppTerminatedEvent(
...
+  appId: PathId,
+  taskId: Task.Id,
+  version: Timestamp,
+  health: Health,
```
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/event/Events.scala]: Why the complete health object? 
This event can only be thrown if there were consecutive failures, that are reported via `FailedHealthCheck`.

**Comment by aquamatthias** [comment]
@janisz Thanks for this contribution!
I added some comments and questions.

File: src/main/scala/mesosphere/marathon/event/Events.scala (hunk 5 above)
Comment (janisz) [inline src/main/scala/mesosphere/marathon/event/Events.scala]: I thougt it will be nice to have more details with event. I'll reduce it to keep only `lastFailureCause`

File: src/main/scala/mesosphere/marathon/event/Events.scala (hunk 4 above)
Comment (janisz) [inline src/main/scala/mesosphere/marathon/event/Events.scala]: I added a note in 
* docs/docs/event-bus.md
* docs/docs/rest-api/mesosphere/marathon/api/v2/AppsResource_create.md

File: src/main/scala/mesosphere/marathon/state/TaskFailure.scala (hunk 2 above)
Comment (janisz) [inline src/main/scala/mesosphere/marathon/state/TaskFailure.scala]: Good point. Fixed

File: src/main/scala/mesosphere/marathon/event/Events.scala (hunk 4 above)
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/event/Events.scala]: 1) Cool. Please add to this PR (I do not see that change)
2) What I originally meant was even simpler: can you define that class under https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/event/Events.scala#L118

Comment (janisz) [inline src/main/scala/mesosphere/marathon/event/Events.scala]: Fixed

**Comment by aquamatthias** [comment]
@janisz Looks good to me. Thanks!
