### PR TITLE
Fixes #4129

### LINKED ISSUE #4129: TaskOpProcessorImplTest is flaky
```
*** 1 TEST FAILED ***
TaskOpProcessorImplTest:
- process update with failing taskRepository.store and load also fails *** FAILED *** (51 milliseconds)
  Vector([INFO] Not leader therefore not reconciling tasks, [WARN] task [app.2725bc54-500d-11e6-81fc-8e8154cad073] of app [/app]: try to recover from failed MesosUpdate(LaunchedEphemeral(task [app.2725bc54-500d-11e6-81fc-8e8154cad073],AgentInfo(host.some,None,List()),2016-07-22T13:06:50.296Z,Status(2016-07-22T13:06:50.296Z,None,None),List()),Running(Some(task_id {
    value: "baaec3c0-4fe8-4953-8e1c-637df0cb5048"
  }
  state: TASK_RUNNING
  )),2015-04-09T12:30:00.000Z), [WARN] task [app.2725bc54-500d-11e6-81fc-8e8154cad073] of app [/app]: task reloading failed as well) had size 3 instead of expected size 2 (TaskOpProcessorImplTest.scala:209)
  org.scalatest.exceptions.TestFailedException:
  at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
  at org.scalatest.Matchers$ResultOfHaveWordForExtent.size(Matchers.scala:2747)
  at mesosphere.marathon.core.task.tracker.impl.TaskOpProcessorImplTest$$anonfun$6.apply$mcV$sp(TaskOpProcessorImplTest.scala:209)
  at mesosphere.marathon.core.task.tracker.impl.TaskOpProcessorImplTest$$anonfun$6.apply(TaskOpProcessorImplTest.scala:173)
  at mesosphere.marathon.core.task.tracker.impl.TaskOpProcessorImplTest$$anonfun$6.apply(TaskOpProcessorImplTest.scala:173)
  at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
  at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
  at mesosphere.marathon.core.task.tracker.impl.TaskOpProcessorImplTest.withFixture(TaskOpProcessorImplTest.scala:30)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175)
  at mesosphere.marathon.core.task.tracker.impl.TaskOpProcessorImplTest.org$scalatest$BeforeAndAfter$$super$runTest(TaskOpProcessorImplTest.scala:30)
  at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200)
  at mesosphere.marathon.core.task.tracker.impl.TaskOpProcessorImplTest.runTest(TaskOpProcessorImplTest.scala:30)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208)
  at mesosphere.marathon.core.task.tracker.impl.TaskOpProcessorImplTest.runTests(TaskOpProcessorImplTest.scala:30)
  at org.scalatest.Suite$class.run(Suite.scala:1424)
  at mesosphere.marathon.core.task.tracker.impl.TaskOpProcessorImplTest.org$scalatest$BeforeAndAfterAll$$super$run(TaskOpProcessorImplTest.scala:30)
  at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
  at mesosphere.marathon.core.task.tracker.impl.TaskOpProcessorImplTest.org$scalatest$FunSuiteLike$$super$run(TaskOpProcessorImplTest.scala:30)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212)
  at mesosphere.marathon.core.task.tracker.impl.TaskOpProcessorImplTest.org$scalatest$BeforeAndAfter$$super$run(TaskOpProcessorImplTest.scala:30)
  at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241)
  at mesosphere.marathon.core.task.tracker.impl.TaskOpProcessorImplTest.run(TaskOpProcessorImplTest.scala:30)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:357)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:502)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by meichstedt**
by making sure there are no MarathonSchedulerServiceTimers lurking around

### CODE REVIEW

File: src/test/scala/mesosphere/marathon/MarathonSchedulerServiceTest.scala [hunk 1]
```diff
@@ -194,6 +189,8 @@ class MarathonSchedulerServiceTest
       override def newTimer() = mockTimer
     }
 
+    schedulerService.timer = mockTimer
```
Comment (gkleiman) [inline src/test/scala/mesosphere/marathon/MarathonSchedulerServiceTest.scala]: If we add this, can we then remove the overridden method in line 189?

File: src/test/scala/mesosphere/marathon/MarathonSchedulerServiceTest.scala [hunk 2]
```diff
@@ -233,6 +228,8 @@ class MarathonSchedulerServiceTest
...
```
Comment (gkleiman) [inline src/test/scala/mesosphere/marathon/MarathonSchedulerServiceTest.scala]: Same as above (but with line 228)

**Comment by gkleiman** [comment]
@meichstedt LGTM, just two minor comments.

File: src/test/scala/mesosphere/marathon/MarathonSchedulerServiceTest.scala (hunk 1 above)
Comment (meichstedt) [inline src/test/scala/mesosphere/marathon/MarathonSchedulerServiceTest.scala]: No, the test relies on the timer instance being the same – if the `newTimer` is not overridden, a new timer will be created (instead of the mock).

Not a very nice test, but I resisted refactoring everything ...

File: src/test/scala/mesosphere/marathon/MarathonSchedulerServiceTest.scala (hunk 2 above)
Comment (meichstedt) [inline src/test/scala/mesosphere/marathon/MarathonSchedulerServiceTest.scala]: also: same as above ;)

**Comment by meichstedt** [comment]
The `MarathonHealthCheckManagerTest` keeps failing although it wasn't changed and wasn't flaky before afaik. Our CI infra seems to have a problem.

**Comment by aquamatthias** [comment]
Thanks

**Comment by aquamatthias** [comment]
@meichstedt  Please cherry pick in 1.2
