### PR TITLE
[Master] Fixes #3047 by introducing a exponential backoff for unresponsive hosts.

### LINKED ISSUE #3047: Event callbacks hold on to unresponsive hosts
When using event callbacks, an unresponsive host will be tried six times for every event. We'd like the option of a specified number of failed endpoint connections or a specified period of endpoint unavailability to trigger the removal of that endpoint.

### PR DESCRIPTION
**Pull request by aquamatthias**
Also a couple of metrics are introduced to have better insights.

### CODE REVIEW

File: src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala [hunk 1]
```diff
@@ -1,52 +1,114 @@
 package mesosphere.marathon.event.http
 
+import java.lang.System.currentTimeMillis
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: I'd like `Clock` better and I am not a friend of prefix-less imports since they make determining the origin of a method more difficult.

File: src/test/scala/mesosphere/marathon/event/http/HttpEventActorTest.scala [hunk 2]
```diff
@@ -0,0 +1,128 @@
...
+    Then("The callback listener is rate limited")
+    waitUntil("Wait for rate limiting 2 subscribers", 1.second) {
+      aut.underlyingActor.limiter("host1").backoffUntil.isDefined && aut.underlyingActor.limiter("host2").backoffUntil.isDefined
+    }
+  }
+
+  ignore("If a message is send to a slow subscriber") {
+    Given("A HttpEventActor with 1 subscriber")
+    val aut = TestActorRef(new NoHttpEventActor(Set("host1")))
+    responseAction = () => { Thread.sleep(100); response }
```
Comment (kolloch) [inline src/test/scala/mesosphere/marathon/event/http/HttpEventActorTest.scala]: Use a clock and make this right. :)

**Comment by kolloch** [comment]
99% there :)

File: src/main/scala/mesosphere/marathon/event/http/HttpEventModule.scala [hunk 3]
```diff
@@ -25,8 +25,17 @@ trait HttpEventConfiguration extends ScallopConf {
     required = false,
     noshort = true).map(parseHttpEventEndpoints)
 
+  lazy val httpEventCallbackSlowConsumerTimeout = opt[Long]("http_event_callback_slow_consumer_timeout",
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventModule.scala]: Please also add to command-line-flags.md

File: src/main/scala/mesosphere/marathon/event/http/HttpEventModule.scala [hunk 4]
```diff
@@ -25,8 +25,17 @@ trait HttpEventConfiguration extends ScallopConf {
...
+    descr = "A http event callback consumer is considered slow, if the delivery takes longer than this timeout (ms)",
+    required = false,
+    noshort = true,
+    default = Some(10.seconds.toMillis)
+  )
+
   private[this] def parseHttpEventEndpoints(str: String): List[String] =
     str.split(',').map(_.trim).toList
+
+  def slowConsumerTimeout: Long = httpEventCallbackSlowConsumerTimeout()
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventModule.scala]: I think that I do not particularly like this shortCut.

File: src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala (hunk 1 above)
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: Jup

File: src/main/scala/mesosphere/marathon/event/http/HttpEventModule.scala (hunk 3 above)
Comment (aquamatthias) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventModule.scala]: Good point. Thanks.

File: src/test/scala/mesosphere/marathon/event/http/HttpEventActorTest.scala (hunk 2 above)
Comment (aquamatthias) [inline src/test/scala/mesosphere/marathon/event/http/HttpEventActorTest.scala]: Yes :+1:

**Comment by aquamatthias** [comment]
@kolloch separate commit with your suggestions - hopefully easy to review.
If ok I will squash the commits.

**Comment by kolloch** [comment]
Nice, looks good! Squash and I'll merge.

I noticed #3109 by reviewing this. It would be nice if you could follow up with this.

**Comment by aquamatthias** [comment]
@meichstedt  This Fix should also go into 0.13.1 and 0.14.1
