### PR TITLE
Fixes #3047 by introducing a exponential backoff for unresponsive hosts.

### LINKED ISSUE #3047: Event callbacks hold on to unresponsive hosts
When using event callbacks, an unresponsive host will be tried six times for every event. We'd like the option of a specified number of failed endpoint connections or a specified period of endpoint unavailability to trigger the removal of that endpoint.

### PR DESCRIPTION
**Pull request by aquamatthias**
Also a couple of metrics are introduced to have better insights.

### CODE REVIEW

**Comment by aquamatthias** [comment]
I guess we changed settings in a way, that travis can not build any longer...
On my machine the tests were green.

File: src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala [hunk 1]
```diff
@@ -2,53 +2,91 @@ package mesosphere.marathon.event.http
...
 import spray.httpx.PlayJsonSupport
-import mesosphere.marathon.api.v2.json.Formats._
 
 import scala.concurrent.Future
-import scala.util.{ Failure, Success }
+import scala.concurrent.duration._
+import scala.util.Success
+import System.currentTimeMillis
+
+object HttpEventActor {
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: Not the fault of this PR but some documentation about what this actor does and what the implementation goals are would be nice.

File: src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala [hunk 2]
```diff
@@ -2,53 +2,91 @@ package mesosphere.marathon.event.http
...
+  case class NotificationFailed(url: String)
+  case class NotificationSuccess(url: String)
+  case class NotificationSlow(url: String)
+
+  case class EventNotificationLimit(failed: Long, deadLine: Option[Deadline]) {
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: what does `failed` mean? docs... what's the deadline? a deadline of a single call??

Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: ah, deadline is more like `backOffUntil`, and `failed` is a somehow scoped failure counter...

File: src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala [hunk 3]
```diff
@@ -2,53 +2,91 @@ package mesosphere.marathon.event.http
...
   implicit val ec = HttpEventModule.executionContext
   implicit val timeout = HttpEventModule.timeout
+  val pipeline: HttpRequest => Future[HttpResponse] = addHeader("Accept", "application/json") ~> sendReceive
+  var limiter = Map.empty[String, EventNotificationLimit].withDefaultValue(NoLimit)
 
-  val pipeline: HttpRequest => Future[HttpResponse] = (
-    addHeader("Accept", "application/json")
-    ~> sendReceive)
+  //metrics
+  val metricOutstandingRequests = metrics.counter("service.mesosphere.marathon.event.http.outstanding-requests")
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: metrics in codahale may only be registered once. Since actors can be restarted, please create an additional object for the metrics that survives actor restarts.

File: src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala [hunk 4]
```diff
@@ -2,53 +2,91 @@ package mesosphere.marathon.event.http
...
   def receive: Receive = {
-    case event: MarathonEvent =>
-      broadcast(event)
-    case _ =>
-      log.warning("Message not understood!")
+    case event: MarathonEvent     => broadcast(event)
+    case NotificationSuccess(url) => limiter += url -> NoLimit
+    case NotificationSlow(url)    => limiter += url -> limiter(url).nextFailed
+    case NotificationFailed(url)  => limiter += url -> limiter(url).nextFailed
+    case _                        => log.warning("Message not understood!")
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: Since you treat slow/failed the same right now, I would simplify the code by getting rid of `NotificationSlow`. Or do you distinguish somewhere else?

File: src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala (hunk 3 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: documentation for the metrics would be nice, too, but I don't insist ;)

File: src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala [hunk 5]
```diff
@@ -2,53 +2,91 @@ package mesosphere.marathon.event.http
...
     log.info("POSTing to all endpoints.")
-    (subscribersKeeper ? GetSubscribers).mapTo[EventSubscribers].foreach {
-      _.urls.foreach { post(_, event) }
+    val me = self
+    (subscribersKeeper ? GetSubscribers).mapTo[EventSubscribers].foreach { subscribers =>
+      val (active, limited) = subscribers.urls.partition(limiter(_).notLimited)
+      if (limited.nonEmpty) log.info(s"Will not send event ${event.eventType} to unresponsive hosts: $limited")
+      metricDroppedEvent.mark(limited.size)
+      active.foreach(post(_, event, me))
     }
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: This would be a good place to delete limiter entries for subscribers that no longer exist... Or am I missing the cleanup code?

File: src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala [hunk 6]
```diff
@@ -2,53 +2,91 @@ package mesosphere.marathon.event.http
...
+    }
+    response.onComplete {
       case Success(res) =>
-        if (res.status.isFailure)
-          log.warning(s"Failed to post $event to $urlString")
-
-      case Failure(t) =>
-        log.warning(s"Failed to post $event to $urlString", t)
+        if (res.status.isFailure) log.debug(s"No success response for post $event to $url")
+        val inTime = (currentTimeMillis() - start) < conf.slowConsumerTimeout
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: So HTTP-level failures (500, ...) are not treated as failures? I think it is more polite doing so because if the receiving end is overloaded, we will desist. Of course, this changes the behavior a bit.

Then, (because we back off and prevent spamming the logs), I would at least log the HTTP status code + status string as warning.

File: src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala [hunk 7]
```diff
@@ -2,53 +2,91 @@ package mesosphere.marathon.event.http
...
+        eventActor ! (if (inTime) NotificationSuccess(url) else NotificationSlow(url))
+      case _ =>
+        log.warning(s"Failed to post $event to $url")
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: You do not want to spam the log with stack traces here? Or you want to keep using akka logging? 

Anyway, maybe the exception name+message would already provide some more info.

File: src/main/scala/mesosphere/marathon/event/http/HttpEventModule.scala [hunk 8]
```diff
@@ -26,8 +25,17 @@ trait HttpEventConfiguration extends ScallopConf {
     required = false,
     noshort = true).map(parseHttpEventEndpoints)
 
+  lazy val httpEventCallbackSlowConsumerTimeout = opt[Long]("http_endpoint_slow_consumer_duration",
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventModule.scala]: scala variable name does not match CLI string. I guess the string is incorrect.

File: src/main/scala/mesosphere/marathon/event/http/HttpEventModule.scala [hunk 9]
```diff
@@ -26,8 +25,17 @@ trait HttpEventConfiguration extends ScallopConf {
...
+    descr = "A http consumer is considered slow, if the delivery takes longer than this timeout (ms)",
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventModule.scala]: you probably want to adjust this as well, even if it is abstract enough to match callbacks, too, in principle ;)

File: src/test/scala/mesosphere/marathon/event/http/HttpEventActorTest.scala [hunk 10]
```diff
@@ -0,0 +1,112 @@
...
+    }
+  }
+
+  test("If a message is send to non existing subscribers") {
+    Given("A HttpEventActor with 2 subscribers")
+    val aut = TestActorRef(new NoHttpEventActor(Set("host1", "host2")))
+    responseAction = () => throw new RuntimeException("Can not connect")
+
+    When("An event is send to the actor")
+    aut ! EventStreamAttached("remote")
```
Comment (kolloch) [inline src/test/scala/mesosphere/marathon/event/http/HttpEventActorTest.scala]: you also can use `out.receive` here to synchronously call the actor.

File: src/test/scala/mesosphere/marathon/event/http/HttpEventActorTest.scala [hunk 11]
```diff
@@ -0,0 +1,112 @@
...
+    Then("The callback listener is rate limited")
+    waitUntil("Wait for rate limiting 2 subscribers", 1.second) {
+      aut.underlyingActor.limiter("host1").deadLine.isDefined && aut.underlyingActor.limiter("host2").deadLine.isDefined
+    }
+  }
+
+  test("If a message is send to a slow subscriber") {
+    Given("A HttpEventActor with 1 subscriber")
+    val aut = TestActorRef(new NoHttpEventActor(Set("host1")))
+    responseAction = () => { Thread.sleep(100); response }
```
Comment (kolloch) [inline src/test/scala/mesosphere/marathon/event/http/HttpEventActorTest.scala]: Ouch, sleeps in tests. Should I less that pass for releasing-0.10? I wouldn't like that on master...

Alternatively, you can virtualize your time by making the method to determine the time `protected` and overridable so that you can mock it for testing.

File: src/test/scala/mesosphere/marathon/event/http/HttpEventActorTest.scala [hunk 12]
```diff
@@ -0,0 +1,112 @@
...
+    EventFilter.info(start = "Will not send event event_stream_attached to unresponsive hosts: Set(host1)") intercept {
+      aut ! EventStreamAttached("remote")
+    }
+
+    And("The message is send to the other subscriber")
+    waitUntil("Wait for 1 subscribers to get notified", 1.second) {
+      aut.underlyingActor.requests.size == 1
+    }
+  }
+
```
Comment (kolloch) [inline src/test/scala/mesosphere/marathon/event/http/HttpEventActorTest.scala]: Nice tests!

Some more test cases:

* limiters for subscribers that do not exist anymore are cleaned up.
* HTTP status != 2xx are logged.

File: src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala [hunk 13]
```diff
@@ -2,53 +2,91 @@ package mesosphere.marathon.event.http
...
 
   def broadcast(event: MarathonEvent): Unit = {
+    metricSendEvent.mark()
     log.info("POSTing to all endpoints.")
-    (subscribersKeeper ? GetSubscribers).mapTo[EventSubscribers].foreach {
-      _.urls.foreach { post(_, event) }
+    val me = self
+    (subscribersKeeper ? GetSubscribers).mapTo[EventSubscribers].foreach { subscribers =>
+      val (active, limited) = subscribers.urls.partition(limiter(_).notLimited)
+      if (limited.nonEmpty) log.info(s"Will not send event ${event.eventType} to unresponsive hosts: $limited")
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: Nit-pick: I don't like "`Set(...)`" in log messages. But that's not blocking a merge...

File: src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala [hunk 14]
```diff
@@ -2,53 +2,91 @@ package mesosphere.marathon.event.http
...
+  val pipeline: HttpRequest => Future[HttpResponse] = addHeader("Accept", "application/json") ~> sendReceive
+  var limiter = Map.empty[String, EventNotificationLimit].withDefaultValue(NoLimit)
 
-  val pipeline: HttpRequest => Future[HttpResponse] = (
-    addHeader("Accept", "application/json")
-    ~> sendReceive)
+  //metrics
+  val metricOutstandingRequests = metrics.counter("service.mesosphere.marathon.event.http.outstanding-requests")
+  val metricSendEvent = metrics.meter("service.mesosphere.marathon.event.http.send")
+  val metricDroppedEvent = metrics.meter("service.mesosphere.marathon.event.http.dropped-events")
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: I think that the metric name is slightly misleading. The events themselves are not dropped but only calling certain callbacks. It is confusing that "send" is measured per event and "dropped-events" per callback. I do like the current position of the metrics, though. So keep the semantic but rename the metrics? E.g.:

* "send" => "events-processed"
* "dropped-events" => "skipped-rate-limited-callbacks" or "skipped-callbacks"

File: src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala [hunk 15]
```diff
@@ -2,53 +2,91 @@ package mesosphere.marathon.event.http
...
+  val metricResponseTime = metrics.timer("service.mesosphere.marathon.event.http.response-time")
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: "callback-response-time" would be clear to me.

Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: Intuitively, I am missing "failed-callbacks"/"slow-callbacks" as metrics. What do you think?

File: src/main/java/mesosphere/marathon/metrics/Metrics.scala [hunk 16]
```diff
@@ -64,6 +68,11 @@ class Metrics @Inject() (val registry: MetricRegistry) {
 }
 
 object Metrics {
+  class Counter(counter: com.codahale.metrics.Counter) {
```
Comment (kolloch) [inline src/main/java/mesosphere/marathon/metrics/Metrics.scala]: Actually, this is great. We missed the `Counter` type before and used stuff like the `AtomicIntGauge` instead. I am just not sure whether it's a good idea to introduce this in this patch.

Either way, it probably makes sense to create an issue and change `master` to using counters instead of `AtomicIntGauge`?

Also, please document that it is a gauge, since counter is not a metric category in statsd, I wouldn't know where to find it otherwise.

File: src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala (hunk 3 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: Usually, we use "metrics.name" to create the metrics name in combination with `MetricPrefixes`. I am really not sure if I like that approach but for consistency it would be better to stick to that, I guess.

**Comment by kolloch** [comment]
Great functionality!

I wrote some comments...

File: src/test/scala/mesosphere/marathon/event/http/HttpEventActorTest.scala (hunk 11 above)
Comment (aquamatthias) [inline src/test/scala/mesosphere/marathon/event/http/HttpEventActorTest.scala]: I will ignore this test. In master we should use clock instead of System.currentTimeMillis

File: src/test/scala/mesosphere/marathon/event/http/HttpEventActorTest.scala (hunk 10 above)
Comment (aquamatthias) [inline src/test/scala/mesosphere/marathon/event/http/HttpEventActorTest.scala]: Not 100% sure - the synchronous thing will help here.

File: src/main/java/mesosphere/marathon/metrics/Metrics.scala (hunk 16 above)
Comment (aquamatthias) [inline src/main/java/mesosphere/marathon/metrics/Metrics.scala]: Counters and Gauges are a separate thing in codahale metrics. Don't know what to document here if it is statsd specific?

**Comment by aquamatthias** [comment]
Thanks for the comments! Hope I addressed them all.

File: src/test/scala/mesosphere/marathon/event/http/HttpEventActorTest.scala (hunk 12 above)
Comment (aquamatthias) [inline src/test/scala/mesosphere/marathon/event/http/HttpEventActorTest.scala]: Added a test for "unlimiting" a previous limited subscriber.

File: src/main/java/mesosphere/marathon/metrics/Metrics.scala (hunk 16 above)
Comment (kolloch) [inline src/main/java/mesosphere/marathon/metrics/Metrics.scala]: You are right. For some reason, I didn't realize that it is a distinct metrics type.

File: src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala (hunk 4 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: Ack.

File: src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala (hunk 7 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: Ack.

File: src/main/scala/mesosphere/marathon/event/http/HttpEventModule.scala (hunk 8 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventModule.scala]: Ack

File: src/main/scala/mesosphere/marathon/event/http/HttpEventModule.scala (hunk 9 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventModule.scala]: Ack

File: src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala (hunk 13 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: Ack, thanks.

File: src/main/java/mesosphere/marathon/metrics/Metrics.scala (hunk 16 above)
Comment (kolloch) [inline src/main/java/mesosphere/marathon/metrics/Metrics.scala]: Ack.

**Comment by kolloch** [comment]
Please investigate test failures. Otherwise, LGTM!

File: src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala [hunk 17]
```diff
@@ -1,54 +1,114 @@
...
 
-  def post(urlString: String, event: MarathonEvent): Unit = {
-    log.info("Sending POST to:" + urlString)
+  def post(url: String, event: MarathonEvent, eventActor: ActorRef): Unit = {
+    log.info("Sending POST to:" + url)
 
-    val request = Post(urlString, eventToJson(event))
+    metrics.outstandingCallbacks.inc()
+    val request = Post(url, eventToJson(event))
     val response = pipeline(request)
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala]: Is it difficult to specify timeouts for individual requests?

**Comment by aquamatthias** [comment]
@kolloch the tests consistently fail without this patch - pretty sure this is not introduced by this PR. Hopefully fixed the shaky assertions.

**Comment by aquamatthias** [comment]
I run into all shaky integration tests with this PR. I am pretty sure, the problem is not related to this PR.
The unit and integration tests run fine on my local machine.
I will create another PR based on master, so we can be sure about that.

**Comment by kolloch** [comment]
:ship: !
