### PR TITLE
Fixes #1215, serialize calculation of DeploymentPlans

### LINKED ISSUE #1215: Possible race condition on simultaneous application launch
Hi Folks!

I'm running into a problem that appears at first glance to be a race condition on application launch. 

If I launch multiple (in my case, 4) apps at the same time by POSTing to /v2/apps, I notice two things: 
1. They are all four assigned the same (formerly available) port (e.g., port 10000)
2. I can only delete one of them via the UI or the REST API; the others have to be scaled down to zero before I can successfully delete them.

The outcome of the first symptom is sort of humorous, actually... the haproxy bridge configures port 10000 (in this example) against all four worker tasks, so that as I refresh, the proxy switches between the different apps. In the short term, I'm calling this RAaaS (Random Application as a Service) ;)

I modified my launcher to protect app creation, with a 500ms delay between them. The symptoms that I'm seeing go away.

I know I haven't given any actionable details: logs, payloads, etc, but I wanted to throw this out and see what folks think. If it seems like it may be an issue in Marathon and/or Mesos, let me know and I'll try to come up with a bash script or something to reproduce it.

I'm running on Marathon 0.7.6, as built by Mesosphere; against Mesos 0.21.1, also built by Mesosphere. 

Many thanks,
--cb

### PR DESCRIPTION
**Pull request by kolloch**
in GroupManager.update.

The GroupManager.update method was not designed to be called concurrently.
It was wrapped in a synchronized block which was ineffective since most of
the computation happened asynchronously in Futures.

This patch introduces a SerializeExecution helper which can be used to
substitute such incorrect usages of synchronized.

### CODE REVIEW

File: src/main/scala/mesosphere/util/SerializeExecutionActor.scala [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+  def apply[T](actorRefFactory: ActorRefFactory, actorName: String): SerializeExecution = {
+    new SerializeExecution(actorRefFactory, actorName)
+  }
+}
+
+class SerializeExecution private (actorRefFactory: ActorRefFactory, actorName: String) {
+  import SerializeExecution.log
+
+  private[this] val props = Props[SerializeExecutionActor]()
+  private[this] val actorRef = actorRefFactory.actorOf(props, actorName)
```
Comment (drexin) [inline src/main/scala/mesosphere/util/SerializeExecutionActor.scala]: Could you think of a better name for this?

File: src/main/scala/mesosphere/util/SerializeExecutionActor.scala [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+  import SerializeExecutionActor.{ log, Execute }
+
+  private[this] var currentFuture: Future[Unit] = Future.successful(())
+
+  override def receive: Receive = {
+    case Execute(func) =>
+      val replyTo = sender()
+      log.debug(s"$self: Receiving Execute from $replyTo")
+      import context.dispatcher
+      currentFuture = currentFuture flatMap { _ =>
```
Comment (drexin) [inline src/main/scala/mesosphere/util/SerializeExecutionActor.scala]: This looks a bit fragile, can we find a better way to do this?

**Comment by kolloch** [comment]
Anything still missing from your perspective? @drexin

File: src/main/scala/mesosphere/util/SerializeExecutionActor.scala (hunk 2 above)
Comment (kolloch) [inline src/main/scala/mesosphere/util/SerializeExecutionActor.scala]: As discussed, the alternatives are more verbose

**Comment by drexin** [comment]
:100:
