### PR TITLE
Fixes #2951 by handling wrong formats in the constraints reader.

### LINKED ISSUE #2951: Incorrect Constraint lead to an application exception, but should give an error response
Trying to apply a configuration change for a task results in Marathon showing the following error message at the bottom of the dialog box:

"Unknown server error, could not create or apply app."

Syslog shows a stack trace that begins with this:
Jan 11 21:31:03 vagrant marathon[1055]: java.lang.IndexOutOfBoundsException: 1
Jan 11 21:31:03 vagrant marathon[1055]: #011at scala.collection.LinearSeqOptimized$class.apply(LinearSeqOptimized.scala:65) ~[marathon:0.13.0]
Jan 11 21:31:03 vagrant marathon[1055]: #011at scala.collection.immutable.List.apply(List.scala:84) ~[marathon:0.13.0]
Jan 11 21:31:03 vagrant marathon[1055]: #011at mesosphere.marathon.api.v2.json.V2Formats$$anonfun$ConstraintFormat$1.apply(Formats.scala:383) ~[marathon:0.13.0]
Jan 11 21:31:03 vagrant marathon[1055]: #011at mesosphere.marathon.api.v2.json.V2Formats$$anonfun$ConstraintFormat$1.apply(Formats.scala:379) ~[marathon:0.13.0]
Jan 11 21:31:03 vagrant marathon[1055]: #011at play.api.libs.json.JsResult$class.map(JsResult.scala:77) ~[marathon:0.13.0]
Jan 11 21:31:03 vagrant marathon[1055]: #011at play.api.libs.json.JsSuccess.map(JsResult.scala:9) ~[marathon:0.13.0]

Unfortunately I am unable to reproduce the error at this time.

### PR DESCRIPTION
**Pull request by aquamatthias**

### CODE REVIEW

File: src/main/scala/mesosphere/marathon/api/v2/json/Formats.scala [hunk 1]
```diff
@@ -457,13 +457,14 @@ trait V2Formats {
...
-        .setOperator(Operator.valueOf(seq(1)))
-      if (seq.size == 3) builder.setValue(seq(2))
-      builder.build()
+    new Reads[Constraint] {
+      override def reads(json: JsValue): JsResult[Constraint] = json.asOpt[Seq[String]] match {
+        case Some(seq) if seq.size >= 2 && seq.size <= 3 && Operator.values().map(_.toString).contains(seq(1)) =>
+          val builder = Constraint.newBuilder().setField(seq(0)).setOperator(Operator.valueOf(seq(1)))
+          if (seq.size == 3) builder.setValue(seq(2))
+          JsSuccess(builder.build())
+        case _ => JsError("Constraint definition must be an array of strings in format: <key>, <OPERATOR>, [value]")
```
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/api/v2/json/Formats.scala]: what about `<KEY>, <OPERATOR>[, <VALUE>]`?

File: src/test/scala/mesosphere/marathon/api/ConstraintTest.scala [hunk 2]
```diff
@@ -21,6 +22,20 @@ class ConstraintTest extends MarathonSpec {
     shouldMatch("""["jdk","UNLIKE","7"]""", "jdk", Constraint.Operator.UNLIKE, "7")
   }
 
+  test("Read should allow only valid Constraints (regression for #2951)") {
+    import mesosphere.marathon.api.v2.json.Formats._
+    Json.parse("""[]""").asOpt[Constraint] should be('empty)
```
Comment (kolloch) [inline src/test/scala/mesosphere/marathon/api/ConstraintTest.scala]: you can use `empty` instead of `'empty` with the advantage that it is type-checked.

File: src/test/scala/mesosphere/marathon/api/ConstraintTest.scala [hunk 3]
```diff
@@ -21,6 +22,20 @@ class ConstraintTest extends MarathonSpec {
...
+    Json.parse("""["foo", "UNKNOWN"]""").asOpt[Constraint] should be('empty)
+    Json.parse("""["foo", "UNKNOWN", "bla"]""").asOpt[Constraint] should be('empty)
+    Json.parse("""["foo", "CLUSTER", "bla"]""").asOpt[Constraint] should be('defined)
```
Comment (kolloch) [inline src/test/scala/mesosphere/marathon/api/ConstraintTest.scala]: same with `defined`.

**Comment by kolloch** [comment]
Thanks. Much better than before! I have some comments.

**Comment by kolloch** [comment]
Thanks! :rocket:
