### PR TITLE
Enhanced MarathonSchedulerActorTest

### LINKED ISSUE #4534: Enhance MarathonSchedulerActorTest
Add Test:

1.) `all` available Terminal InstanceStatus to the instance and verify explicitly that none of these is sent for reconciliation.

2.) Following Scenario: 
```
Created
Error
Failed
Finished
Killed
Killing
Running
Staging
Starting
Unreachable
Gone
Dropped
Unknown
```
and a verify that status is only sent for
```
Created
Killing
Running
Staging
Starting
Unreachable
```

### PR DESCRIPTION
**Pull request by unterstein**
Fixes #4534

Summary: Enhanced MarathonSchedulerActorTest to be more verbose and explicitly to handle terminal task status

Test Plan: sbt test

Reviewers: meichstedt

Subscribers: marathon-team

Differential Revision: https://phabricator.mesosphere.com/D36

### CODE REVIEW

**Comment by unterstein** [comment]
Same as https://phabricator.mesosphere.com/D36 including @meichstedt `s feedback. Was not able to update the phabricator review :-(

File: src/test/scala/mesosphere/marathon/MarathonSchedulerActorTest.scala [hunk 1]
```diff
@@ -108,6 +108,90 @@ class MarathonSchedulerActorTest extends MarathonActorSupport
...
+      .addTaskFailed(containerName = Some("failed"))
+      .addTaskFinished(containerName = Some("finished"))
+      .addTaskKilled(containerName = Some("killed"))
+      .addTaskGone(containerName = Some("gone"))
+      .addTaskDropped(containerName = Some("dropped"))
+      .addTaskUnknown(containerName = Some("unknown"))
+      .getInstance()
+
+    appRepo.ids() returns Source.single(app.id)
+    instanceTracker.instancesBySpec()(any[ExecutionContext]) returns Future.successful(InstanceTracker.InstancesBySpec.of(InstanceTracker.SpecInstances.forInstances("nope".toPath, Iterable(instance))))
```
Comment (meichstedt) [inline src/test/scala/mesosphere/marathon/MarathonSchedulerActorTest.scala]: Instead of `"nope".toPath`, shouldn't this be `app.id`? Doesn't matter for the test, but it looks like a wrong setup.

File: src/test/scala/mesosphere/marathon/MarathonSchedulerActorTest.scala [hunk 2]
```diff
@@ -108,6 +108,90 @@ class MarathonSchedulerActorTest extends MarathonActorSupport
...
+      .addTaskCreated(containerName = Some("created"))
+      .addTaskKilling(containerName = Some("killing"))
+      .addTaskRunning(containerName = Some("running"))
+      .addTaskStaging(containerName = Some("staging"))
+      .addTaskStarting(containerName = Some("starting"))
+      .addTaskUnreachable(containerName = Some("unreachable"))
+      .getInstance()
+
+    appRepo.ids() returns Source.single(app.id)
+    instanceTracker.instancesBySpec()(any[ExecutionContext]) returns Future.successful(InstanceTracker.InstancesBySpec.of(InstanceTracker.SpecInstances.forInstances("nope".toPath, Iterable(instance))))
```
Comment (meichstedt) [inline src/test/scala/mesosphere/marathon/MarathonSchedulerActorTest.scala]: same as above

**Comment by unterstein** [comment]
Currently rebasing and resolving merge issues.

**Comment by unterstein** [comment]
retest this please

**Comment by unterstein** [comment]
retest this please

**Comment by unterstein** [comment]
retest this please

**Comment by meichstedt** [comment]
Failing integration tests are unrelated (only UnitTests have been changed in this patch)
