### PR TITLE
Fixes #2681 - Circumvent cache if not yet preloaded

### LINKED ISSUE #2681: 0.11.1 -> 0.13.0-RC4 upgrade losing and then killing old tasks
I was testing upgrade from 0.11.1 to 0.13.0-RC4. Every attempted upgrade results in the new 0.13 leader not recognizing existing tasks, and killing all old tasks at once upon the first reconciliation. I can fail over leaders without upgrading in both 0.11->0.11 or 0.13->0.13 without losing tasks, it is only the upgrade 0.11->0.13  that has this issue. By greatly increasing `--reconciliation_initial_delay` I can make it so that the new tasks are launched before the old tasks get killed, however this is far from ideal IMO. 

Attached is part of the logs from the new 0.13 master, running a single app hello with 3 healthy tasks before the upgrade. 3 more tasks are started and the old 3 tasks are killed. I would expect that the old 3 tasks would be recognized and continue running.

[log.txt](https://github.com/mesosphere/marathon/files/39754/log.txt)

### PR DESCRIPTION
**Pull request by kolloch**
I am not completely happy with this patch and still have to test the migration but it should demonstrate the problem.

### CODE REVIEW

**Comment by kolloch** [comment]
I tested changed it to using an Option. If you like the design, I will fix the tests.

File: src/test/scala/mesosphere/marathon/test/Mockito.scala [hunk 1]
```diff
@@ -28,6 +28,10 @@ trait Mockito extends MockitoSugar {
     M.verifyNoMoreInteractions(mocks: _*)
   }
 
+  def reset(mocks: AnyRef*): Unit = {
+    M.reset(mocks: _*)
```
Comment (kolloch) [inline src/test/scala/mesosphere/marathon/test/Mockito.scala]: unused now in the tests but it can be useful so I kept it.

**Comment by meichstedt** [comment]
:+1: for adding missing test cases!
