### PR TITLE
Fix #851 - Allow apps to replace groups without apps

### LINKED ISSUE #851: Groups and Applications may not have the same identifier
I created app `/something/app`, but then I decided that I'd better have `/something/app/service`. I removed `/something/app`, but when I try to create `/something/app/service`, I get an error:

```
Groups and Applications may not have the same identifier
```

I think there should be no error here.

_UPDATE_

The steps to reproduce this problem are:

1. `PUT /v2/apps/something/app`
2. `DELETE /v2/apps/something/app`
3. `PUT /v2/apps/something`, not `PUT /v2/apps/something/app/service`

### PR DESCRIPTION
**Pull request by kolloch**
Since groups are created implicitly by creating apps with nested paths
and not visible yet in the GUI, we allow replacing groups without any apps
by app definitions.

### CODE REVIEW

File: src/main/scala/mesosphere/marathon/api/BeanValidation.scala [hunk 1]
```diff
@@ -76,3 +76,5 @@ trait BeanValidation {
   }
 }
 
+object BeanValidation extends BeanValidation
```
Comment (drexin) [inline src/main/scala/mesosphere/marathon/api/BeanValidation.scala]: Is this being used anywhere?

File: src/main/scala/mesosphere/marathon/api/ModelValidation.scala [hunk 2]
```diff
@@ -288,3 +288,5 @@ trait ModelValidation extends BeanValidation {
   }
 
 }
+
+object ModelValidation extends ModelValidation
```
Comment (drexin) [inline src/main/scala/mesosphere/marathon/api/ModelValidation.scala]: This is only being used in the test. Can we instead just create an anonymous instance in the test?

File: src/main/scala/mesosphere/marathon/state/Group.scala [hunk 3]
```diff
@@ -151,6 +165,12 @@ case class Group(
   def hasNonCyclicDependencies: Boolean = {
     !new CycleDetector[AppDefinition, DefaultEdge](dependencyGraph).detectCycles()
   }
+
+  /** @return true if and only if this group directly or indirectly contains app definitions. */
+  @JsonIgnore
+  def containsApps: Boolean = {
+    apps.nonEmpty || groups.exists(_.containsApps)
```
Comment (drexin) [inline src/main/scala/mesosphere/marathon/state/Group.scala]: This could be a one liner.

**Comment by drexin** [comment]
Aside from my comments LGTM.

File: src/main/scala/mesosphere/marathon/api/BeanValidation.scala (hunk 1 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/api/BeanValidation.scala]: No but in my opinion it should.

I do not like using traits like this. Do you?

File: src/main/scala/mesosphere/marathon/api/ModelValidation.scala (hunk 2 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/api/ModelValidation.scala]: No but in my opinion it should be used everywhere.

I do not like using traits like this. Do you?

File: src/main/scala/mesosphere/marathon/state/Group.scala (hunk 3 above)
Comment (kolloch) [inline src/main/scala/mesosphere/marathon/state/Group.scala]: OK

**Comment by drexin** [comment]
:+1:
